
import type { Product, Category, Review } from '@/types';

export const categories: Category[] = [
  { id: 'cat_el_1', name: 'Smartphones & Accessories', slug: 'smartphones-accessories' },
  { id: 'cat_el_2', name: 'Laptops & Computers', slug: 'laptops-computers' },
  { id: 'cat_el_3', name: 'Audio & Headphones', slug: 'audio-headphones' },
  { id: 'cat_el_4', name: 'Cameras & Drones', slug: 'cameras-drones' },
  { id: 'cat_el_6', name: 'Wearable Technology', slug: 'wearables' },
  { id: 'cat_el_7', name: 'Smart Home Devices', slug: 'smart-home' },
];

export const products: Product[] = [
  {
    id: 'prod_el_1',
    name: 'AuraBeat Pro Wireless Headphones',
    description: 'Immerse yourself in pure audio bliss with AuraBeat Pro. Features active noise-cancellation, 30-hour battery life, and ultra-soft earcups for maximum comfort.',
    price: 249.99,
    imageUrl: 'https://picsum.photos/seed/auraheadphones/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 50,
    features: ['Active Noise Cancellation', 'Bluetooth 5.2', '30-hour battery life', 'Comfort-fit earcups', 'Crystal-clear microphone'],
    sku: 'AU-HP-789',
    brand: 'AuraAudio',
  },
  {
    id: 'prod_el_2',
    name: 'NovaPhone X2 Ultra Smartphone',
    description: 'Experience the future with NovaPhone X2 Ultra. Stunning 120Hz AMOLED display, powerful new-gen processor, and a revolutionary 108MP camera system.',
    price: 999.00,
    imageUrl: 'https://picsum.photos/seed/novaphone/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 35,
    features: ['6.8" 120Hz AMOLED Display', '12GB RAM', '256GB Storage', '108MP Triple Camera', '5G Connectivity'],
    sku: 'SM-NP-X2U',
    brand: 'NovaTech',
  },
  {
    id: 'prod_el_3',
    name: 'ZenithBook Air 14" Laptop',
    description: 'Ultra-portable and powerful, the ZenithBook Air is perfect for professionals and creatives on the go. Feather-light design with all-day battery life.',
    price: 1299.50,
    imageUrl: 'https://picsum.photos/seed/zenithbook/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 25,
    features: ['14" QHD+ Display', 'Latest Gen Intel Core i7', '16GB RAM', '1TB NVMe SSD', 'Backlit Keyboard', 'Thunderbolt 4'],
    sku: 'LT-ZB-A14',
    brand: 'ZenithComputers',
  },
  {
    id: 'prod_el_4',
    name: 'SkyHawk Pro Drone',
    description: 'Capture breathtaking aerial footage with the SkyHawk Pro Drone. Features 4K HDR video, 3-axis gimbal stabilization, and intelligent flight modes.',
    price: 799.00,
    imageUrl: 'https://picsum.photos/seed/skyhawkdrone/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 40,
    features: ['4K HDR Video @ 60fps', '30-min Flight Time', '5-mile Range', 'Obstacle Avoidance', 'Foldable Design'],
    sku: 'DR-SH-P4K',
    brand: 'AeroVision',
  },
  {
    id: 'prod_el_6',
    name: 'ChronoFit Active Smartwatch',
    description: 'Stay connected and track your fitness goals with the ChronoFit Active. ECG, SpO2 monitoring, built-in GPS, and a vibrant always-on display.',
    price: 329.00,
    imageUrl: 'https://picsum.photos/seed/chronofitwatch/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 70,
    features: ['ECG & SpO2 Monitor', 'Built-in GPS', 'Water Resistant (5ATM)', '1.4" AMOLED Display', '7-Day Battery Life'],
    sku: 'WT-CF-A05',
    brand: 'ChronoWear',
  },
  {
    id: 'prod_el_7',
    name: 'AuraHome Smart Hub Pro',
    description: 'Control your smart home devices with ease using the AuraHome Smart Hub Pro. Compatible with Zigbee, Z-Wave, and Wi-Fi devices.',
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/aurahomehub/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 55,
    features: ['Multi-protocol support', 'Voice assistant integration', 'Customizable automation scenes', 'Secure local control'],
    sku: 'SH-AH-PRO',
    brand: 'AuraHome',
  },
  // New Smartphones
  {
    id: 'prod_el_9',
    name: 'Apple iPhone 15 Pro',
    description: 'The latest iPhone with Pro features, A17 Bionic chip, and advanced camera system.',
    price: 1199.00,
    imageUrl: 'https://picsum.photos/seed/iphone15pro/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 30,
    features: ['ProMotion Display', 'A17 Bionic Chip', '48MP Main Camera', 'Titanium Design', 'Action Button'],
    sku: 'SM-AP-IP15P',
    brand: 'Apple',
  },
  {
    id: 'prod_el_10',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Experience Galaxy AI with the S24 Ultra. Powerful performance, stunning display, and an incredible camera system with S Pen support.',
    price: 1299.00,
    imageUrl: 'https://picsum.photos/seed/galaxys24ultra/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 25,
    features: ['Dynamic AMOLED 2X', 'Snapdragon 8 Gen 3 for Galaxy', '200MP Main Camera', 'Built-in S Pen', 'Galaxy AI Features'],
    sku: 'SM-SS-S24U',
    brand: 'Samsung',
  },
  {
    id: 'prod_el_11',
    name: 'Xiaomi 14 Ultra',
    description: 'Co-engineered with Leica, the Xiaomi 14 Ultra offers a professional-grade photography experience in a smartphone.',
    price: 1099.00,
    imageUrl: 'https://picsum.photos/seed/xiaomi14ultra/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 40,
    features: ['Leica Quad Camera System', 'Snapdragon 8 Gen 3', '120Hz AMOLED Display', 'HyperCharge Technology', 'Ceramic Back'],
    sku: 'SM-XM-14U',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_12',
    name: 'Vivo X100 Pro',
    description: 'Capture stunning portraits and low-light shots with the Vivo X100 Pro, featuring ZEISS optics and advanced imaging technology.',
    price: 949.00,
    imageUrl: 'https://picsum.photos/seed/vivox100pro/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 35,
    features: ['ZEISS Co-engineered Camera', 'Dimensity 9300 Chipset', '120Hz LTPO AMOLED', '100W FlashCharge', 'V3 Imaging Chip'],
    sku: 'SM-VV-X100P',
    brand: 'Vivo',
  },
  {
    id: 'prod_el_13',
    name: 'Realme GT 5 Pro',
    description: 'Flagship performance at a competitive price. The Realme GT 5 Pro offers a powerful processor, a bright display, and fast charging.',
    price: 799.00,
    imageUrl: 'https://picsum.photos/seed/realmegt5pro/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 50,
    features: ['Snapdragon 8 Gen 3', '144Hz AMOLED Display', 'Sony IMX890 OIS Camera', '240W SuperVOOC Charge', 'Stainless Steel Vapor Cooling'],
    sku: 'SM-RM-GT5P',
    brand: 'Realme',
  },
  // New Laptops
  {
    id: 'prod_el_14',
    name: 'MacBook Air 13" M3 Chip',
    description: 'The incredibly thin and light MacBook Air, now supercharged by the M3 chip. Delivers powerhouse performance and up to 18 hours of battery life.',
    price: 1099.00,
    imageUrl: 'https://picsum.photos/seed/macbookair13m3/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 45,
    features: ['Apple M3 Chip', '13.6-inch Liquid Retina Display', '8GB Unified Memory', '256GB SSD Storage', 'Up to 18 hours battery life', 'Silent, fanless design'],
    sku: 'LT-AP-MBA13M3',
    brand: 'Apple',
  },
  {
    id: 'prod_el_15',
    name: 'MacBook Pro 14" M3 Pro Chip',
    description: 'The MacBook Pro 14” with the M3 Pro chip offers game-changing performance for demanding workflows. Features a stunning Liquid Retina XDR display.',
    price: 1999.00,
    imageUrl: 'https://picsum.photos/seed/macbookpro14m3pro/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 30,
    features: ['Apple M3 Pro Chip', '14.2-inch Liquid Retina XDR Display', '18GB Unified Memory', '512GB SSD Storage', 'ProMotion technology', 'Advanced thermal system'],
    sku: 'LT-AP-MBP14M3P',
    brand: 'Apple',
  },
  {
    id: 'prod_el_16',
    name: 'MacBook Pro 16" M3 Max Chip',
    description: 'The ultimate pro laptop, the MacBook Pro 16” with M3 Max chip takes performance to new heights for the most extreme workflows.',
    price: 3499.00,
    imageUrl: 'https://picsum.photos/seed/macbookpro16m3max/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 20,
    features: ['Apple M3 Max Chip', '16.2-inch Liquid Retina XDR Display', '36GB Unified Memory', '1TB SSD Storage', 'Enhanced media engine', 'Studio-quality mics'],
    sku: 'LT-AP-MBP16M3MAX',
    brand: 'Apple',
  },
  {
    id: 'prod_el_17',
    name: 'iMac 24" M3 Chip',
    description: 'The all-in-one desktop, transformed by the M3 chip. Features a stunning 24-inch 4.5K Retina display in a remarkably thin design.',
    price: 1299.00,
    imageUrl: 'https://picsum.photos/seed/imac24m3/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 25,
    features: ['Apple M3 Chip', '24-inch 4.5K Retina Display', '8GB Unified Memory', '256GB SSD Storage', '1080p FaceTime HD camera', 'Magic Keyboard with Touch ID'],
    sku: 'DT-AP-IMAC24M3',
    brand: 'Apple',
  },
  {
    id: 'prod_el_18',
    name: 'ASUS ROG Zephyrus G14 (2024)',
    description: 'The ROG Zephyrus G14 is a highly portable gaming powerhouse with a stunning Nebula Display and the latest AMD Ryzen AI processors.',
    price: 1599.99,
    imageUrl: 'https://picsum.photos/seed/asusrogzephyrusg14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 35,
    features: ['AMD Ryzen 9 8000 Series with AI', 'NVIDIA GeForce RTX 4070 Laptop GPU', '14-inch QHD+ 165Hz Nebula Display', '16GB DDR5 RAM', '1TB PCIe 4.0 SSD', 'AniMe Matrix™ display'],
    sku: 'LT-AS-ROGZG14',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_19',
    name: 'ASUS Zenbook Duo (2024)',
    description: 'Experience ultimate productivity with the revolutionary ASUS Zenbook Duo, featuring two full-size OLED touchscreens.',
    price: 1999.99,
    imageUrl: 'https://picsum.photos/seed/asuszenbookduo/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 22,
    features: ['Intel Core Ultra 9 Processor', 'Dual 14-inch 3K OLED Touchscreens', '32GB LPDDR5X RAM', '1TB PCIe 4.0 SSD', 'Detachable full-size keyboard', 'AI-powered features'],
    sku: 'LT-AS-ZBDUO24',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_20',
    name: 'ASUS Vivobook Pro 16X OLED',
    description: 'Unleash your creative power with the Vivobook Pro 16X OLED, featuring a stunning 4K OLED display and high-performance components.',
    price: 1799.00,
    imageUrl: 'https://picsum.photos/seed/asusvivobookpro16x/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 28,
    features: ['Intel Core i9 H-Series Processor', 'NVIDIA GeForce RTX 4060 Laptop GPU', '16-inch 4K OLED Display', '32GB DDR5 RAM', '1TB PCIe SSD', 'ASUS DialPad'],
    sku: 'LT-AS-VBPRO16X',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_21',
    name: 'ASUS TUF Gaming A15',
    description: 'The ASUS TUF Gaming A15 is a durable gaming laptop that delivers reliable performance for all your favorite titles.',
    price: 1199.00,
    imageUrl: 'https://picsum.photos/seed/asustufgaminga15/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 40,
    features: ['AMD Ryzen 7 7000 Series Processor', 'NVIDIA GeForce RTX 4050 Laptop GPU', '15.6-inch FHD 144Hz Display', '16GB DDR5 RAM', '512GB PCIe SSD', 'Military-grade durability'],
    sku: 'LT-AS-TUFA15',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_22',
    name: 'Xiaomi Book Pro 14 (2024)',
    description: 'The Xiaomi Book Pro 14 offers a sleek design, a high-resolution display, and powerful performance for professionals.',
    price: 999.00,
    imageUrl: 'https://picsum.photos/seed/xiaomibookpro14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 33,
    features: ['Intel Core Ultra 7 Processor', 'Intel Arc Graphics', '14-inch 2.8K OLED Display', '16GB LPDDR5 RAM', '1TB PCIe 4.0 SSD', 'CNC unibody design'],
    sku: 'LT-XM-BPRO14',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_23',
    name: 'Xiaomi Book Air 13',
    description: 'An ultra-thin and lightweight laptop from Xiaomi, perfect for portability without sacrificing essential performance.',
    price: 749.00,
    imageUrl: 'https://picsum.photos/seed/xiaomibookair13/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 42,
    features: ['Intel Core i5 U-Series Processor', 'Intel Iris Xe Graphics', '13.3-inch FHD OLED Display', '16GB RAM', '512GB SSD', 'Slim and light chassis'],
    sku: 'LT-XM-BAIR13',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_24',
    name: 'RedmiBook Pro 15 (2024)',
    description: 'The RedmiBook Pro 15 balances performance and value, featuring a high-refresh-rate display and capable hardware.',
    price: 899.00,
    imageUrl: 'https://picsum.photos/seed/redmibookpro15/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 38,
    features: ['AMD Ryzen 7 7840HS Processor', 'Integrated AMD Radeon Graphics', '15.6-inch 3.2K 120Hz Display', '16GB DDR5 RAM', '512GB PCIe SSD', 'Full-metal body'],
    sku: 'LT-XM-RMBP15',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_25',
    name: 'Xiaomi Gaming Laptop G Pro',
    description: 'A performance-focused gaming laptop from Xiaomi with aggressive styling and powerful cooling.',
    price: 1399.00,
    imageUrl: 'https://picsum.photos/seed/xiaomigaminggpro/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 25,
    features: ['Intel Core i7 H-Series Processor', 'NVIDIA GeForce RTX 4060 Laptop GPU', '16-inch QHD 240Hz Display', '16GB DDR5 RAM', '1TB PCIe SSD', 'Advanced cooling system'],
    sku: 'LT-XM-GLGPRO',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_26',
    name: 'HP Spectre x360 14 (2024)',
    description: 'The HP Spectre x360 14 is a premium 2-in-1 laptop with a stunning OLED display, versatile design, and AI-enhanced features.',
    price: 1649.99,
    imageUrl: 'https://picsum.photos/seed/hpspectrex36014/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 30,
    features: ['Intel Core Ultra 7 Processor', 'Intel Arc Graphics', '14-inch 2.8K OLED Touchscreen', '16GB RAM', '1TB SSD', 'HP Stylus included', 'AI NPU'],
    sku: 'LT-HP-SPX36014',
    brand: 'HP',
  },
  {
    id: 'prod_el_27',
    name: 'HP Envy x360 15',
    description: 'A versatile and stylish 2-in-1 laptop, the HP Envy x360 15 is perfect for both work and creativity.',
    price: 999.99,
    imageUrl: 'https://picsum.photos/seed/hpenvyx36015/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 36,
    features: ['AMD Ryzen 7 Processor', 'AMD Radeon Graphics', '15.6-inch FHD IPS Touchscreen', '16GB RAM', '512GB SSD', 'Bang & Olufsen Audio'],
    sku: 'LT-HP-ENVX36015',
    brand: 'HP',
  },
  {
    id: 'prod_el_28',
    name: 'HP Omen Transcend 14',
    description: 'The HP Omen Transcend 14 is one of the lightest 14-inch gaming laptops, featuring a vibrant OLED screen and powerful performance.',
    price: 1699.99,
    imageUrl: 'https://picsum.photos/seed/hpomentranscend14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 20,
    features: ['Intel Core Ultra 9 Processor', 'NVIDIA GeForce RTX 4070 Laptop GPU', '14-inch 2.8K OLED 120Hz Display', '32GB RAM', '1TB SSD', 'HyperX Audio'],
    sku: 'LT-HP-OMTR14',
    brand: 'HP',
  },
  {
    id: 'prod_el_29',
    name: 'HP Pavilion Aero 13',
    description: 'The HP Pavilion Aero 13 is incredibly lightweight and offers excellent performance for everyday tasks and portability.',
    price: 799.99,
    imageUrl: 'https://picsum.photos/seed/hppavilionaero13/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 45,
    features: ['AMD Ryzen 5 Processor', 'AMD Radeon Graphics', '13.3-inch WUXGA Display', '16GB RAM', '512GB SSD', 'Weighs less than 1kg'],
    sku: 'LT-HP-PAVAERO13',
    brand: 'HP',
  },
  {
    id: 'prod_el_30',
    name: 'Lenovo Yoga 9i (14-inch, Gen 9)',
    description: 'The Lenovo Yoga 9i combines stunning design with powerful performance and innovative features, including a rotating soundbar.',
    price: 1799.00,
    imageUrl: 'https://picsum.photos/seed/lenovoyoga9i14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 28,
    features: ['Intel Core Ultra 7 Processor', 'Intel Arc Graphics', '14-inch 4K OLED PureSight Touch Display', '16GB RAM', '1TB SSD', 'Bowers & Wilkins rotating soundbar'],
    sku: 'LT-LN-Y9I14G9',
    brand: 'Lenovo',
  },
  {
    id: 'prod_el_31',
    name: 'Lenovo Legion Pro 7i (Gen 9)',
    description: 'Experience top-tier gaming performance with the Lenovo Legion Pro 7i, featuring AI-tuned power and advanced cooling.',
    price: 2499.00,
    imageUrl: 'https://picsum.photos/seed/lenovolegionpro7i/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 18,
    features: ['Intel Core i9 HX-Series Processor', 'NVIDIA GeForce RTX 4080 Laptop GPU', '16-inch WQXGA 240Hz Display', '32GB DDR5 RAM', '1TB PCIe SSD', 'Legion ColdFront 5.0 cooling'],
    sku: 'LT-LN-LPRO7IG9',
    brand: 'Lenovo',
  },
  {
    id: 'prod_el_32',
    name: 'Lenovo ThinkPad X1 Carbon (Gen 12)',
    description: 'The iconic ThinkPad X1 Carbon, now even lighter and more powerful, designed for ultimate business productivity and durability.',
    price: 2100.00,
    imageUrl: 'https://picsum.photos/seed/lenovothinkpadx1c12/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 32,
    features: ['Intel Core Ultra Processors with vPro', 'Intel Arc Graphics', '14-inch Display options up to OLED', 'Up to 64GB RAM', 'Up to 2TB SSD', 'Legendary ThinkPad keyboard'],
    sku: 'LT-LN-TPX1C12',
    brand: 'Lenovo',
  },
  {
    id: 'prod_el_33',
    name: 'Lenovo IdeaPad Slim 5 (16-inch AMD)',
    description: 'A stylish and capable everyday laptop, the IdeaPad Slim 5 offers a large display and reliable performance for work and entertainment.',
    price: 799.00,
    imageUrl: 'https://picsum.photos/seed/lenovoideapadslim5/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 40,
    features: ['AMD Ryzen 7 U-Series Processor', 'AMD Radeon Graphics', '16-inch WUXGA IPS Display', '16GB RAM', '512GB SSD', 'Privacy Shutter'],
    sku: 'LT-LN-IPSLIM5A',
    brand: 'Lenovo',
  },
  // New Audio & Headphones
  {
    id: 'prod_el_34',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise canceling headphones with incredible sound quality and a lightweight, comfortable design.',
    price: 399.99,
    imageUrl: 'https://picsum.photos/seed/sonywh1000xm5/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 60,
    features: ['Best-in-class Noise Cancellation', '30-hour battery life', 'Multipoint connection', 'Speak-to-Chat', 'Lightweight design'],
    sku: 'AU-SN-WHXM5',
    brand: 'Sony',
  },
  {
    id: 'prod_el_35',
    name: 'Bose QuietComfort Ultra Headphones',
    description: 'World-class noise cancellation, stunning immersive audio, and luxurious comfort. These are the ultimate Bose experience.',
    price: 429.00,
    imageUrl: 'https://picsum.photos/seed/boseqcultra/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 50,
    features: ['Bose Immersive Audio', 'CustomTune technology', 'Up to 24-hour battery life', 'Premium materials', 'Multipoint Bluetooth'],
    sku: 'AU-BS-QCUH',
    brand: 'Bose',
  },
  {
    id: 'prod_el_36',
    name: 'Apple AirPods Max',
    description: 'A perfect balance of exhilarating high-fidelity audio and the effortless magic of AirPods. The ultimate personal listening experience is here.',
    price: 549.00,
    imageUrl: 'https://picsum.photos/seed/airpodsmax/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 35,
    features: ['Active Noise Cancellation', 'Transparency Mode', 'Spatial Audio with dynamic head tracking', 'Computational audio', 'Knit-mesh canopy and memory foam earcups'],
    sku: 'AU-AP-MAX01',
    brand: 'Apple',
  },
  {
    id: 'prod_el_37',
    name: 'Sennheiser Momentum 4 Wireless',
    description: 'Enjoy best-in-class sound with Sennheiser\'s audiophile-inspired acoustic system. Exceptional comfort and an outstanding 60-hour battery life.',
    price: 379.95,
    imageUrl: 'https://picsum.photos/seed/sennheisermomentum4/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 45,
    features: ['Signature Sennheiser Sound', 'Adaptive Noise Cancellation', '60-hour battery life', 'Lightweight, foldable design', 'Smart Touch Controls'],
    sku: 'AU-SH-MOM4',
    brand: 'Sennheiser',
  },
  {
    id: 'prod_el_38',
    name: 'JBL Tour One M2 Headphones',
    description: 'True Adaptive Noise Cancelling headphones that deliver JBL Pro Sound for an immersive audio experience. Smart features for seamless connectivity.',
    price: 299.95,
    imageUrl: 'https://picsum.photos/seed/jbltouronem2/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 55,
    features: ['True Adaptive Noise Cancelling', 'JBL Pro Sound', 'Up to 50 hours of playtime', '4-mic technology for clear calls', 'Smart Ambient Aware'],
    sku: 'AU-JB-TOURM2',
    brand: 'JBL',
  },
  {
    id: 'prod_el_39',
    name: 'Sony WF-1000XM5 Earbuds',
    description: 'The best noise canceling earbuds, now even smaller and lighter, with breathtaking sound quality and AI-powered call quality.',
    price: 299.99,
    imageUrl: 'https://picsum.photos/seed/sonywf1000xm5/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 70,
    features: ['Industry-leading Noise Canceling', 'New Dynamic Driver X', 'AI-based noise reduction for calls', 'Multipoint connection', '8-hour battery (24 with case)'],
    sku: 'AU-SN-WFXM5',
    brand: 'Sony',
  },
  {
    id: 'prod_el_40',
    name: 'Bose QuietComfort Ultra Earbuds',
    description: 'These next-generation earbuds feature groundbreaking Bose Immersive Audio and world-class noise cancellation that’s quieter than ever before.',
    price: 299.00,
    imageUrl: 'https://picsum.photos/seed/boseqcultraearbuds/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 65,
    features: ['Bose Immersive Audio', 'World-class noise cancellation', 'CustomTune technology', 'Secure and comfortable fit', 'Up to 6 hours battery (24 with case)'],
    sku: 'AU-BS-QCUEB',
    brand: 'Bose',
  },
  {
    id: 'prod_el_41',
    name: 'Apple AirPods Pro (2nd Gen)',
    description: 'Re-engineered for even richer audio experiences. Next-level Active Noise Cancellation and Adaptive Transparency, plus Personalized Spatial Audio.',
    price: 249.00,
    imageUrl: 'https://picsum.photos/seed/airpodspro2/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 80,
    features: ['H2 Apple Chip', 'Active Noise Cancellation', 'Adaptive Transparency', 'Personalized Spatial Audio', 'Touch control', 'MagSafe Charging Case'],
    sku: 'AU-AP-PRO2',
    brand: 'Apple',
  },
  {
    id: 'prod_el_42',
    name: 'Sennheiser Momentum True Wireless 4',
    description: 'Delivering unparalleled sound quality and next-gen features like Auracast and LE Audio, with adaptive noise cancellation.',
    price: 299.95,
    imageUrl: 'https://picsum.photos/seed/sennheisermomentumtw4/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 50,
    features: ['Sennheiser TrueResponse sound', 'Adaptive Noise Cancellation', 'Future-proof technologies (Auracast, LE Audio)', 'Up to 30 hours playtime with case', 'Customizable touch controls'],
    sku: 'AU-SH-MTW4',
    brand: 'Sennheiser',
  },
  {
    id: 'prod_el_43',
    name: 'JBL Live Pro 2 TWS Earbuds',
    description: 'True Wireless earbuds with Adaptive Noise Cancelling, Smart Ambient, and clear calls thanks to 6 beamforming mics.',
    price: 149.95,
    imageUrl: 'https://picsum.photos/seed/jbllivepro2/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 75,
    features: ['Adaptive Noise Cancelling with Smart Ambient', 'JBL Signature Sound', 'Up to 40 hours of battery life (10 in buds)', '6 mics for perfect calls', 'Oval TubesTM for better comfort'],
    sku: 'AU-JB-LIVEP2',
    brand: 'JBL',
  },
  {
    id: 'prod_el_44',
    name: 'Anker Soundcore Liberty 4 NC',
    description: 'Noise cancelling earbuds with a new standard of noise reduction, crisp sound, and long playtime. Reduces noise by up to 98.5%.',
    price: 99.99,
    imageUrl: 'https://picsum.photos/seed/soundcoreliberty4nc/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 90,
    features: ['Reduces noise by up to 98.5%', 'Adaptive ANC 2.0', 'Hi-Res Wireless audio', '10-hour playtime (50 with case)', 'Wireless charging'],
    sku: 'AU-AK-LIB4NC',
    brand: 'Anker Soundcore',
  },
  {
    id: 'prod_el_45',
    name: 'Audio-Technica ATH-M50xBT2 Headphones',
    description: 'The legendary M50x studio sound, now wireless. Critically acclaimed sonic performance praised by top audio engineers and pro audio reviewers.',
    price: 199.00,
    imageUrl: 'https://picsum.photos/seed/audiotechnicam50xbt2/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 40,
    features: ['Critically acclaimed M50x sound', '45 mm large-aperture drivers', 'Up to 50 hours of continuous use', 'Multipoint pairing', 'Optional wired connection'],
    sku: 'AU-AT-M50XBT2',
    brand: 'Audio-Technica',
  },
  {
    id: 'prod_el_46',
    name: 'Beats Studio Pro Headphones',
    description: 'Immersive listening with fully adaptive Active Noise Cancelling, Personalized Spatial Audio, and lossless audio via USB-C.',
    price: 349.99,
    imageUrl: 'https://picsum.photos/seed/beatsstudiopro/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 50,
    features: ['Fully Adaptive Active Noise Cancelling', 'Personalized Spatial Audio', 'Lossless Audio via USB-C', 'Up to 40 hours of battery life', 'Enhanced call quality'],
    sku: 'AU-BT-STPRO',
    brand: 'Beats by Dre',
  },
  {
    id: 'prod_el_47',
    name: 'Shure AONIC 50 Gen 2 Headphones',
    description: 'Studio-quality sound with adjustable noise cancellation and new Spatialized Audio. Crafted from premium materials for unmatched comfort.',
    price: 349.00,
    imageUrl: 'https://picsum.photos/seed/shureaonic50gen2/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 30,
    features: ['Spatialized Audio technology', 'Adjustable noise cancellation', 'Up to 45 hours battery life', 'Premium, durable design', 'Customizable EQ via ShurePlus PLAY app'],
    sku: 'AU-SR-AON50G2',
    brand: 'Shure',
  },
  {
    id: 'prod_el_48',
    name: 'Bang & Olufsen Beoplay HX Headphones',
    description: 'Comfortable, long-lasting headphones with impressive sound and Adaptive Active Noise Cancellation. Experience sound as the artist intended.',
    price: 499.00,
    imageUrl: 'https://picsum.photos/seed/bobeoplayhx/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 25,
    features: ['Adaptive Active Noise Cancellation', 'Up to 35 hours with ANC', 'Authentic sound with custom 40mm drivers', 'Lightweight and comfortable', 'Elegant Danish design'],
    sku: 'AU-BO-BPHX',
    brand: 'Bang & Olufsen',
  },
  {
    id: 'prod_el_49',
    name: 'Samsung Galaxy Buds2 Pro',
    description: 'Ultimate Hi-Fi sound in your ear. Intelligent ANC, comfortable fit, and seamless connectivity with your Galaxy devices.',
    price: 229.99,
    imageUrl: 'https://picsum.photos/seed/galaxybuds2pro/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 60,
    features: ['24-bit Hi-Fi Audio', 'Intelligent Active Noise Cancellation', 'Enhanced 360 Audio', 'Comfortable ergonomic design', 'Seamless Galaxy device switching'],
    sku: 'AU-SS-GB2PRO',
    brand: 'Samsung',
  },
  {
    id: 'prod_el_50',
    name: 'Google Pixel Buds Pro',
    description: 'Premium earbuds with Active Noise Cancellation, Silent Seal™, and immersive sound that adapts to you. Plus, hands-free Google Assistant.',
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/pixelbudspro/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 55,
    features: ['Active Noise Cancellation with Silent Seal™', 'Volume EQ', 'Up to 11 hours listening time (31 with case)', 'Multipoint Bluetooth', 'Hands-free Google Assistant'],
    sku: 'AU-GG-PBP',
    brand: 'Google',
  },
  {
    id: 'prod_el_51',
    name: 'JBL Charge 5 Portable Speaker',
    description: 'Portable Bluetooth speaker with powerful JBL Original Pro Sound, an optimized long-excursion driver, separate tweeter, and dual bass radiators.',
    price: 179.95,
    imageUrl: 'https://picsum.photos/seed/jblcharge5/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 70,
    features: ['JBL Original Pro Sound', '20 hours of playtime', 'IP67 waterproof and dustproof', 'PartyBoost compatible', 'Built-in powerbank'],
    sku: 'AU-JB-CHG5',
    brand: 'JBL',
  },
  {
    id: 'prod_el_52',
    name: 'Bose SoundLink Flex Bluetooth Speaker',
    description: 'Delivers clear, deep sound that’s powerful enough to fill any room and loud enough for any outdoor adventure. Rugged, waterproof design.',
    price: 149.00,
    imageUrl: 'https://picsum.photos/seed/bosesoundlinkflex/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 65,
    features: ['Astonishing sound for its size', 'PositionIQ™ technology for optimal sound', 'IP67 waterproof and dustproof', 'Up to 12 hours per charge', 'Rugged and portable'],
    sku: 'AU-BS-SLFLEX',
    brand: 'Bose',
  },
  {
    id: 'prod_el_53',
    name: 'Sony LinkBuds S Truly Wireless Earbuds',
    description: 'Super small and light, these earbuds provide comfort you can wear for hours, with smart features and high-quality noise canceling.',
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/sonylinkbudss/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 50,
    features: ['Small, light, and comfortable', 'High-quality noise canceling', 'Integrated Processor V1', 'Precise Voice Pickup technology', 'Adaptive Sound Control'],
    sku: 'AU-SN-LBS',
    brand: 'Sony',
  },
  // New Cameras & Drones
  {
    id: 'prod_el_54',
    name: 'DJI Mavic 3 Pro Drone',
    description: 'Flagship drone with triple-camera system, Hasselblad main camera, and omnidirectional obstacle sensing for professional aerial cinematography.',
    price: 2199.00,
    imageUrl: 'https://picsum.photos/seed/djimavic3pro/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 25,
    features: ['Hasselblad 4/3 CMOS Camera', 'Dual Tele Cameras', '43-Min Max Flight Time', 'Omnidirectional Obstacle Sensing', 'O3+ Transmission'],
    sku: 'DR-DJI-M3P',
    brand: 'DJI',
  },
  {
    id: 'prod_el_55',
    name: 'DJI Mini 4 Pro Drone',
    description: 'Mini to the max. Lightweight and foldable drone with 4K HDR video, true vertical shooting, and extended battery life.',
    price: 759.00,
    imageUrl: 'https://picsum.photos/seed/djimin4pro/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 50,
    features: ['Under 249g', '4K/60fps HDR True Vertical Shooting', 'Omnidirectional Obstacle Sensing', 'Extended Battery Life', 'FocusTrack'],
    sku: 'DR-DJI-MIN4P',
    brand: 'DJI',
  },
  {
    id: 'prod_el_56',
    name: 'DJI Air 3 Drone',
    description: 'Dual primary cameras, 46-min max flight time, omnidirectional obstacle sensing, and O4 HD video transmission. Elevate your aerial shots.',
    price: 1099.00,
    imageUrl: 'https://picsum.photos/seed/djiair3/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 40,
    features: ['Dual Wide-Angle & Medium Tele Cameras', '46-Min Max Flight Time', 'Omnidirectional Obstacle Sensing', 'O4 HD Video Transmission', 'APAS 5.0'],
    sku: 'DR-DJI-AIR3',
    brand: 'DJI',
  },
  {
    id: 'prod_el_57',
    name: 'DJI Avata FPV Drone',
    description: 'Experience the thrill of immersive flight with DJI Avata. Compact and agile, it’s perfect for flying in tight spaces.',
    price: 629.00, // Drone only, often bundled
    imageUrl: 'https://picsum.photos/seed/djiavata/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 35,
    features: ['Immersive Flight Experience', 'Intuitive Motion Controller', '4K Stabilized Video', 'Built-in Propeller Guard', 'Turtle Mode'],
    sku: 'DR-DJI-AVATA',
    brand: 'DJI',
  },
  {
    id: 'prod_el_58',
    name: 'Sony Alpha 7 IV Mirrorless Camera',
    description: 'A true hybrid, the Alpha 7 IV blends outstanding image quality for stills and movies with advanced connectivity and reliability.',
    price: 2499.99,
    imageUrl: 'https://picsum.photos/seed/sonya7iv/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 30,
    features: ['33MP Full-Frame Exmor R CMOS Sensor', 'BIONZ XR Processor', '4K 60p Video Recording', 'Real-time Eye AF', '5-Axis SteadyShot INSIDE Stabilization'],
    sku: 'CAM-SN-A7M4',
    brand: 'Sony',
  },
  {
    id: 'prod_el_59',
    name: 'Canon EOS R6 Mark II Mirrorless Camera',
    description: 'A versatile full-frame mirrorless camera offering powerful photo and video capabilities for enthusiasts and professionals alike.',
    price: 2499.00,
    imageUrl: 'https://picsum.photos/seed/canoneosr6mkii/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 28,
    features: ['24.2MP Full-Frame CMOS Sensor', 'DIGIC X Image Processor', '4K60 10-Bit Internal Video', 'Dual Pixel CMOS AF II', 'In-Body Image Stabilizer'],
    sku: 'CAM-CN-R6MK2',
    brand: 'Canon',
  },
  {
    id: 'prod_el_60',
    name: 'Nikon Z8 Mirrorless Camera',
    description: 'Essentially a mini Z9, the Z8 offers flagship performance in a more compact body, excelling in both stills and video.',
    price: 3999.95,
    imageUrl: 'https://picsum.photos/seed/nikonz8/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 20,
    features: ['45.7MP FX-Format Stacked CMOS Sensor', 'EXPEED 7 Image Processor', '8K30p and 4K120p Video', 'Subject Detection AF', 'Blackout-Free Real Live Viewfinder'],
    sku: 'CAM-NK-Z8',
    brand: 'Nikon',
  },
  {
    id: 'prod_el_61',
    name: 'Fujifilm X-T5 Mirrorless Camera',
    description: 'A stills-focused APS-C camera that combines classic, tactile controls with modern imaging technology and a high-resolution sensor.',
    price: 1699.95,
    imageUrl: 'https://picsum.photos/seed/fujifilmxt5/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 32,
    features: ['40MP APS-C X-Trans CMOS 5 HR BSI Sensor', 'X-Processor 5', '6.2K30p Video Recording', '7-Stop In-Body Image Stabilization', 'Classic Dial-Based Controls'],
    sku: 'CAM-FJ-XT5',
    brand: 'Fujifilm',
  },
  {
    id: 'prod_el_62',
    name: 'GoPro HERO12 Black Action Camera',
    description: 'The latest HERO camera with incredible image quality, HyperSmooth 6.0 video stabilization, and an extended battery life.',
    price: 399.99,
    imageUrl: 'https://picsum.photos/seed/goprohero12/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 60,
    features: ['5.3K60 + 4K120 Video', 'HyperSmooth 6.0 Stabilization', 'HDR Photos & Video', 'Waterproof to 33ft', 'Enduro Battery for longer runtime'],
    sku: 'CAM-GP-H12B',
    brand: 'GoPro',
  },
  {
    id: 'prod_el_63',
    name: 'Sony ZV-E10 Mirrorless Vlog Camera',
    description: 'Designed for vloggers, the ZV-E10 features a large APS-C sensor, versatile lens options, and dedicated vlogging features.',
    price: 799.99, // With kit lens
    imageUrl: 'https://picsum.photos/seed/sonyzve10/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 45,
    features: ['24.2MP APS-C Exmor CMOS Sensor', 'Side Flip-out Vari-Angle LCD', 'Product Showcase Setting', 'Background Defocus', 'Directional 3-Capsule Mic'],
    sku: 'CAM-SN-ZVE10K',
    brand: 'Sony',
  },
  {
    id: 'prod_el_64',
    name: 'Canon EOS R50 Mirrorless Camera',
    description: 'A compact and lightweight APS-C mirrorless camera perfect for content creators looking to step up from a smartphone.',
    price: 679.99,
    imageUrl: 'https://picsum.photos/seed/canoneosr50/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 38,
    features: ['24.2MP APS-C CMOS Sensor', 'DIGIC X Processor', '4K30p Uncropped Video', 'Dual Pixel CMOS AF II', 'Compact and Lightweight'],
    sku: 'CAM-CN-R50',
    brand: 'Canon',
  },
  {
    id: 'prod_el_65',
    name: 'Nikon Z fc Mirrorless Camera',
    description: 'A stylish APS-C mirrorless camera with a retro design inspired by the classic Nikon FM2, combined with modern Z series technology.',
    price: 959.95,
    imageUrl: 'https://picsum.photos/seed/nikonzfc/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 33,
    features: ['20.9MP DX-Format CMOS Sensor', 'EXPEED 6 Processor', '4K UHD Video Recording', 'Vari-Angle Touchscreen', 'Retro Design with Physical Dials'],
    sku: 'CAM-NK-ZFC',
    brand: 'Nikon',
  },
  {
    id: 'prod_el_66',
    name: 'Panasonic LUMIX GH6 Mirrorless Camera',
    description: 'A powerhouse for video creators, the GH6 offers unlimited C4K/4K 60p 10-bit recording, 5.7K 60p, and advanced stabilization.',
    price: 2199.99,
    imageUrl: 'https://picsum.photos/seed/panasonicgh6/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 22,
    features: ['25.2MP Live MOS Micro Four Thirds Sensor', '5.7K 60p, 4K 120p HFR Video', 'ProRes 422 HQ Recording', 'Dual I.S. 2 (7.5-Stop)', 'Active Cooling System'],
    sku: 'CAM-PN-GH6',
    brand: 'Panasonic',
  },
  {
    id: 'prod_el_67',
    name: 'DJI Osmo Action 4 Camera',
    description: 'Pushing the boundaries of action cameras with exceptional low-light performance, 10-bit color depth, and long-lasting battery.',
    price: 399.00,
    imageUrl: 'https://picsum.photos/seed/djiosmoaction4/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 55,
    features: ['1/1.3-inch Sensor for Low-Light', '4K/120fps & 155° Ultra-Wide FOV', '10-bit & D-Log M Color Performance', 'RockSteady 3.0+ Stabilization', 'Waterproof to 18m'],
    sku: 'CAM-DJI-OA4',
    brand: 'DJI',
  },
  {
    id: 'prod_el_68',
    name: 'Autel EVO Lite+ Drone',
    description: 'Features a 1-inch CMOS sensor, 6K/30fps video, and adjustable aperture. A powerful alternative for serious aerial photographers and videographers.',
    price: 1549.00,
    imageUrl: 'https://picsum.photos/seed/autelevoliteplus/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 26,
    features: ['1-inch CMOS Sensor', '6K/30fps Video', 'Adjustable Aperture f/2.8-f/11', '40-Min Flight Time', 'Dynamic Track 2.1'],
    sku: 'DR-AUT-ELP',
    brand: 'Autel Robotics',
  },
  {
    id: 'prod_el_69',
    name: 'Insta360 X3 Action Camera',
    description: 'Capture everything with 5.7K 360° video, an invisible selfie stick, and powerful AI editing features. Pocket-sized and versatile.',
    price: 449.99,
    imageUrl: 'https://picsum.photos/seed/insta360x3/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 48,
    features: ['5.7K 360° Capture', 'Dual 1/2" 48MP Sensors', 'FlowState Stabilization', 'Invisible Selfie Stick Effect', 'AI Editing Suite'],
    sku: 'CAM-I360-X3',
    brand: 'Insta360',
  },
  {
    id: 'prod_el_70',
    name: 'Sony Alpha 6700 Mirrorless Camera',
    description: 'Advanced APS-C camera with AI-based subject recognition, impressive image quality, and professional video features.',
    price: 1399.99,
    imageUrl: 'https://picsum.photos/seed/sonya6700/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 30,
    features: ['26MP APS-C BSI CMOS Sensor', 'BIONZ XR Processor & AI Processing Unit', '4K 120p Video', 'AI-Powered Autofocus', '5-Axis In-Body Image Stabilization'],
    sku: 'CAM-SN-A6700',
    brand: 'Sony',
  },
  {
    id: 'prod_el_71',
    name: 'Canon PowerShot V10 Vlog Camera',
    description: 'A compact, pocketable vlogging camera with a built-in stand, stereo microphone, and skin-smoothing filter.',
    price: 429.99,
    imageUrl: 'https://picsum.photos/seed/canonv10/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 42,
    features: ['1.0-inch CMOS Sensor', '4K30p Video Recording', 'Built-in Wide-Angle Lens', 'Integrated Stand & Stereo Mic', 'Vertical Video Support'],
    sku: 'CAM-CN-PSV10',
    brand: 'Canon',
  },
  {
    id: 'prod_el_72',
    name: 'Olympus OM-D E-M10 Mark IV Mirrorless Camera',
    description: 'A compact and lightweight Micro Four Thirds camera perfect for travel and everyday photography, with in-body image stabilization.',
    price: 699.99,
    imageUrl: 'https://picsum.photos/seed/olympusomdem10mkiv/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 36,
    features: ['20MP Live MOS Sensor', 'TruePic VIII Image Processor', '5-Axis In-Body Image Stabilization', '4K UHD Video Recording', 'Flip-Down Touchscreen'],
    sku: 'CAM-OM-EM10M4',
    brand: 'OM System (Olympus)',
  },
  {
    id: 'prod_el_73',
    name: 'DJI RS 3 Mini Gimbal Stabilizer',
    description: 'Lightweight and compact 3-axis gimbal designed for mirrorless cameras, offering professional-level stabilization on the go.',
    price: 369.00,
    imageUrl: 'https://picsum.photos/seed/djirs3mini/600/400',
    categoryId: 'cat_el_4', // Can be an accessory but often sold with cameras
    categoryName: 'Cameras & Drones',
    stock: 50,
    features: ['Lightweight Design (795g)', 'Supports up to 2kg Payload', '3rd-Gen RS Stabilization Algorithm', 'Native Vertical Shooting', '1.4" Full-Color Touchscreen'],
    sku: 'ACC-DJI-RS3MINI',
    brand: 'DJI',
  },
  // New Wearable Technology
  {
    id: 'prod_el_74',
    name: 'Apple Watch Series 9',
    description: 'The latest Apple Watch with a brighter display, faster S9 SiP, and new double tap gesture for interaction.',
    price: 399.00,
    imageUrl: 'https://picsum.photos/seed/applewatch9/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 80,
    features: ['Brighter Always-On Retina display', 'S9 SiP with Double Tap gesture', 'Advanced health sensors (ECG, Blood Oxygen)', 'Crash Detection & Fall Detection', 'Carbon Neutral options'],
    sku: 'WT-AP-W9',
    brand: 'Apple',
  },
  {
    id: 'prod_el_75',
    name: 'Samsung Galaxy Watch 6 Classic',
    description: 'Timeless design with a rotating bezel, advanced health monitoring, and seamless Galaxy ecosystem integration.',
    price: 399.99,
    imageUrl: 'https://picsum.photos/seed/galaxywatch6classic/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 75,
    features: ['Rotating Bezel', 'Sapphire Crystal Glass', 'BioActive Sensor (ECG, BIA, Heart Rate)', 'Sleep Coaching', 'Customizable Watch Faces'],
    sku: 'WT-SS-GW6C',
    brand: 'Samsung',
  },
  {
    id: 'prod_el_76',
    name: 'Fitbit Charge 6 Fitness Tracker',
    description: 'Advanced fitness tracker with Google essentials, heart rate on exercise equipment, and 7 days of battery life.',
    price: 159.95,
    imageUrl: 'https://picsum.photos/seed/fitbitcharge6/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 100,
    features: ['ECG App & EDA Scan App', 'Built-in GPS', 'Google Maps & Wallet', 'Active Zone Minutes', 'Sleep Score'],
    sku: 'WT-FB-CH6',
    brand: 'Fitbit',
  },
  {
    id: 'prod_el_77',
    name: 'Garmin Venu 3 Smartwatch',
    description: 'Purpose-built with advanced health and fitness features and the ability to make calls and send texts from your wrist.',
    price: 449.99,
    imageUrl: 'https://picsum.photos/seed/garminvenu3/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 60,
    features: ['AMOLED Display', 'Body Battery™ Energy Monitoring', 'Advanced Sleep Coaching', 'Built-in Sports Apps & Animated Workouts', 'Wheelchair Mode'],
    sku: 'WT-GM-VENU3',
    brand: 'Garmin',
  },
  {
    id: 'prod_el_78',
    name: 'Xiaomi Smart Band 8 Pro',
    description: 'Large AMOLED display, comprehensive health tracking, and long battery life in a sleek and stylish design.',
    price: 69.99,
    imageUrl: 'https://picsum.photos/seed/xiaomiband8pro/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 120,
    features: ['1.74" AMOLED Display', 'Built-in GPS', 'All-Day SpO2 Monitoring', '150+ Fitness Modes', 'Up to 14-Day Battery Life'],
    sku: 'WT-XM-SB8P',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_79',
    name: 'Google Pixel Watch 2',
    description: 'The helpfulness of Google, now with improved performance, all-day battery life, and new safety features.',
    price: 349.99,
    imageUrl: 'https://picsum.photos/seed/pixelwatch2/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 65,
    features: ['Wear OS by Google', 'Fitbit Health & Fitness Tracking', 'New CPU for smoother performance', 'Safety Check & Emergency Sharing', 'ECG app'],
    sku: 'WT-GG-PW2',
    brand: 'Google',
  },
  {
    id: 'prod_el_80',
    name: 'Amazfit Balance Smartwatch',
    description: 'Focus on mental and physical readiness with AI-powered insights, dual-band GPS, and a lightweight design.',
    price: 229.99,
    imageUrl: 'https://picsum.photos/seed/amazfitbalance/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 55,
    features: ['Zepp OS 3.0 with AI Health Coach', 'Body Composition Measurement', 'Dual-band GPS & Route Import', '1.5" HD AMOLED Display', '14-Day Battery Life'],
    sku: 'WT-AM-BAL',
    brand: 'Amazfit',
  },
  {
    id: 'prod_el_81',
    name: 'Huawei Watch GT 4',
    description: 'Elegant smartwatch with upgraded health monitoring, scientific workout coach, and up to 2 weeks of battery life.',
    price: 279.00,
    imageUrl: 'https://picsum.photos/seed/huaweiwatchgt4/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 70,
    features: ['Geometric Aesthetics Design', 'TruSeen™ 5.5+ Health Monitoring', 'Calorie Management', 'Professional Workout Tracking', 'Wide Compatibility'],
    sku: 'WT-HW-GT4',
    brand: 'Huawei',
  },
  // New Smart Home Devices
  {
    id: 'prod_el_82',
    name: 'Amazon Echo Dot (5th Gen)',
    description: 'Our most popular smart speaker with Alexa, now with an improved audio experience for clearer vocals and deeper bass.',
    price: 49.99,
    imageUrl: 'https://picsum.photos/seed/echodot5/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 150,
    features: ['Improved audio quality', 'Control smart home devices', 'Ask Alexa for anything', 'Privacy controls', 'E-reader support'],
    sku: 'SH-AMZ-ED5',
    brand: 'Amazon',
  },
  {
    id: 'prod_el_83',
    name: 'Google Nest Hub (2nd Gen)',
    description: 'The center of your helpful home. Control your connected home, get news and weather, and enjoy entertainment with this smart display.',
    price: 99.99,
    imageUrl: 'https://picsum.photos/seed/nesthub2/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 100,
    features: ['7" Touchscreen Display', 'Google Assistant built-in', 'Sleep Sensing technology', 'Control compatible devices', 'Stream music and videos'],
    sku: 'SH-GGL-NH2',
    brand: 'Google',
  },
  {
    id: 'prod_el_84',
    name: 'Philips Hue White & Color Ambiance Starter Kit',
    description: 'Start with smart lighting. Includes Hue Bridge and 3 White and color ambiance bulbs. Create personalized lighting scenes.',
    price: 199.99,
    imageUrl: 'https://picsum.photos/seed/philipshuekit/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 80,
    features: ['16 million colors', 'Control with app or voice', 'Sync lights with music and movies', 'Hue Bridge included', 'Expandable system'],
    sku: 'SH-PH-HUEKIT',
    brand: 'Philips Hue',
  },
  {
    id: 'prod_el_85',
    name: 'Ring Video Doorbell Pro 2',
    description: 'Premium video doorbell with 3D Motion Detection, Head-to-Toe HD+ Video, and Two-Way Talk with Audio+.',
    price: 249.99,
    imageUrl: 'https://picsum.photos/seed/ringdoorbellpro2/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 60,
    features: ['1536p HD+ Video', '3D Motion Detection', 'Color Night Vision', 'Alexa Greetings (with subscription)', 'Hardwired installation'],
    sku: 'SH-RG-VDBP2',
    brand: 'Ring',
  },
  {
    id: 'prod_el_86',
    name: 'Wyze Cam v3 Pro',
    description: 'Smart security camera with 2K resolution, color night vision, and integrated spotlight. Indoor/Outdoor use.',
    price: 59.98,
    imageUrl: 'https://picsum.photos/seed/wyzecamv3pro/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 120,
    features: ['2K Resolution', 'Color Night Vision', 'IP65 Weatherproof', 'Motion & Sound Detection', 'Two-Way Audio', 'Integrated Spotlight'],
    sku: 'SH-WZ-CAMV3P',
    brand: 'Wyze',
  },
  {
    id: 'prod_el_87',
    name: 'TP-Link Kasa Smart Plug Mini (4-Pack)',
    description: 'Control your electronics from anywhere using the Kasa app. Schedule lights, fans, and appliances to turn on/off automatically.',
    price: 29.99,
    imageUrl: 'https://picsum.photos/seed/kasasmartplug/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 200,
    features: ['Remote Control via Kasa App', 'Voice Control (Alexa, Google Assistant)', 'Scheduling & Timers', 'Away Mode', 'Compact Design'],
    sku: 'SH-TP-KSP4PK',
    brand: 'TP-Link Kasa',
  },
  {
    id: 'prod_el_88',
    name: 'Ecobee Smart Thermostat Premium',
    description: 'The smarter Wi-Fi thermostat with voice control and a SmartSensor included. Save energy and stay comfortable.',
    price: 249.99,
    imageUrl: 'https://picsum.photos/seed/ecobeethermostat/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 70,
    features: ['Built-in Alexa & Siri support', 'Includes SmartSensor', 'Energy Star certified', 'Learns your schedule', 'HVAC system monitoring'],
    sku: 'SH-ECB-STPREM',
    brand: 'Ecobee',
  },
  {
    id: 'prod_el_89',
    name: 'Arlo Pro 4 Spotlight Camera (3-Pack)',
    description: 'Wire-free security cameras with 2K HDR video, color night vision, and an integrated spotlight. Weather-resistant design.',
    price: 499.99,
    imageUrl: 'https://picsum.photos/seed/arlopro4/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 50,
    features: ['2K HDR Video', 'Integrated Spotlight & Siren', 'Color Night Vision', '160° Diagonal View', 'Weather Resistant', 'Wire-Free'],
    sku: 'SH-ARL-P4SP3PK',
    brand: 'Arlo',
  },
];

export const reviews: Review[] = [
  {
    id: 'rev_el_1',
    productId: 'prod_el_1', // AuraBeat Pro Wireless Headphones
    userName: 'Alice Wonderland',
    rating: 5,
    comment: 'Absolutely love these headphones! The noise cancellation is top-notch and they are so comfortable for long listening sessions.',
    date: '2024-03-15T10:00:00Z',
  },
  {
    id: 'rev_el_2',
    productId: 'prod_el_1', // AuraBeat Pro Wireless Headphones
    userName: 'Bob The Builder',
    rating: 4,
    comment: 'Great sound quality and ANC. The battery life is fantastic. A bit pricey, but worth it.',
    date: '2024-03-20T14:30:00Z',
  },
  {
    id: 'rev_el_3',
    productId: 'prod_el_2', // NovaPhone X2 Ultra Smartphone
    userName: 'Charlie R.',
    rating: 5,
    comment: 'This phone is a beast! Camera is incredible, and it handles everything I throw at it. Display is gorgeous.',
    date: '2024-04-05T09:15:00Z',
  },
  {
    id: 'rev_el_4',
    productId: 'prod_el_3', // ZenithBook Air 14" Laptop
    userName: 'Diana P.',
    rating: 4,
    comment: 'Super light and portable, battery lasts all day. Keyboard is comfortable for typing. Screen is crisp.',
    date: '2024-04-01T11:00:00Z',
  },
  {
    id: 'rev_el_5',
    productId: 'prod_el_6', // ChronoFit Active Smartwatch
    userName: 'Eddie M.',
    rating: 5,
    comment: 'Best smartwatch I\'ve owned. Tracks everything accurately and the screen is very bright outdoors.',
    date: '2024-03-25T16:45:00Z',
  },
  {
    id: 'rev_el_6',
    productId: 'prod_el_4', // SkyHawk Pro Drone
    userName: 'Fiona G.',
    rating: 5,
    comment: 'Incredible drone for the price. Stable flight and amazing video quality. Easy to learn for beginners too!',
    date: '2024-02-28T07:30:00Z',
  },
  {
    id: 'rev_el_8',
    productId: 'prod_el_7', // AuraHome Smart Hub Pro
    userName: 'SmartHomeFan',
    rating: 4,
    comment: 'Connects all my devices seamlessly. App is pretty good, but could use a few more integrations.',
    date: '2024-03-01T12:00:00Z',
  },
  // Reviews for new smartphones
  {
    id: 'rev_el_9',
    productId: 'prod_el_9', // Apple iPhone 15 Pro
    userName: 'TechGuru101',
    rating: 5,
    comment: 'The Action Button is a game changer! Performance is buttery smooth.',
    date: '2024-05-01T10:00:00Z',
  },
  {
    id: 'rev_el_10',
    productId: 'prod_el_9', // Apple iPhone 15 Pro
    userName: 'AppleFanatic',
    rating: 4,
    comment: 'Great phone, but battery life could be a bit better for heavy users.',
    date: '2024-05-03T11:00:00Z',
  },
  {
    id: 'rev_el_11',
    productId: 'prod_el_10', // Samsung Galaxy S24 Ultra
    userName: 'AndroidCentral',
    rating: 5,
    comment: 'Galaxy AI is surprisingly useful. The camera zoom is incredible!',
    date: '2024-05-02T14:00:00Z',
  },
  {
    id: 'rev_el_12',
    productId: 'prod_el_10', // Samsung Galaxy S24 Ultra
    userName: 'PenMaster',
    rating: 5,
    comment: 'Love the S Pen integration. This is the ultimate productivity phone.',
    date: '2024-05-04T15:00:00Z',
  },
  {
    id: 'rev_el_13',
    productId: 'prod_el_11', // Xiaomi 14 Ultra
    userName: 'PhotoPro',
    rating: 5,
    comment: 'Leica partnership really shines. The camera details are stunning.',
    date: '2024-04-28T10:30:00Z',
  },
  {
    id: 'rev_el_14',
    productId: 'prod_el_11', // Xiaomi 14 Ultra
    userName: 'ValueSeeker',
    rating: 4,
    comment: 'Flagship specs without the absolute top-tier price. Great deal.',
    date: '2024-04-30T12:00:00Z',
  },
  {
    id: 'rev_el_15',
    productId: 'prod_el_12', // Vivo X100 Pro
    userName: 'PortraitFan',
    rating: 5,
    comment: 'ZEISS portraits are unmatched. Amazing low-light performance.',
    date: '2024-05-05T09:00:00Z',
  },
  {
    id: 'rev_el_16',
    productId: 'prod_el_12', // Vivo X100 Pro
    userName: 'SpeedyCharge',
    rating: 4,
    comment: 'Super fast charging is a lifesaver. Display is also beautiful.',
    date: '2024-05-06T13:15:00Z',
  },
  {
    id: 'rev_el_17',
    productId: 'prod_el_13', // Realme GT 5 Pro
    userName: 'GamerMobile',
    rating: 5,
    comment: 'Handles all games smoothly. The 144Hz display is a treat.',
    date: '2024-04-25T17:00:00Z',
  },
  {
    id: 'rev_el_18',
    productId: 'prod_el_13', // Realme GT 5 Pro
    userName: 'BudgetKing',
    rating: 4,
    comment: 'Incredible value for the performance you get. Solid all-rounder.',
    date: '2024-04-27T19:30:00Z',
  },
  // Reviews for new laptops
  {
    id: 'rev_el_19',
    productId: 'prod_el_14', // MacBook Air 13" M3 Chip
    userName: 'StudentLife',
    rating: 5,
    comment: 'Perfect for college! So light and the M3 chip is surprisingly powerful. Battery lasts forever.',
    date: '2024-05-10T08:00:00Z',
  },
  {
    id: 'rev_el_20',
    productId: 'prod_el_15', // MacBook Pro 14" M3 Pro Chip
    userName: 'VideoEditorPro',
    rating: 5,
    comment: 'M3 Pro chews through 4K video edits. The XDR display is a dream for color accuracy.',
    date: '2024-05-11T10:30:00Z',
  },
  {
    id: 'rev_el_21',
    productId: 'prod_el_18', // ASUS ROG Zephyrus G14
    userName: 'RoadWarriorGamer',
    rating: 5,
    comment: 'Finally, a portable gaming laptop that doesn\'t compromise on power. The Nebula display is stunning!',
    date: '2024-05-12T14:15:00Z',
  },
  {
    id: 'rev_el_22',
    productId: 'prod_el_19', // ASUS Zenbook Duo (2024)
    userName: 'MultitaskMaster',
    rating: 4,
    comment: 'The dual screens are a productivity game-changer. A bit of a learning curve but so worth it.',
    date: '2024-05-13T09:00:00Z',
  },
  {
    id: 'rev_el_23',
    productId: 'prod_el_22', // Xiaomi Book Pro 14 (2024)
    userName: 'SleekXiaomiFan',
    rating: 4,
    comment: 'Beautiful design and the OLED screen is vibrant. Great performance for the price.',
    date: '2024-05-14T11:45:00Z',
  },
  {
    id: 'rev_el_24',
    productId: 'prod_el_26', // HP Spectre x360 14 (2024)
    userName: 'CreativeConvert',
    rating: 5,
    comment: 'This 2-in-1 is pure luxury. The OLED touch display is responsive and the AI features are a nice touch.',
    date: '2024-05-15T16:20:00Z',
  },
  {
    id: 'rev_el_25',
    productId: 'prod_el_30', // Lenovo Yoga 9i (14-inch, Gen 9)
    userName: 'AudiophileExec',
    rating: 5,
    comment: 'The rotating soundbar is incredible! Laptop itself is powerful and looks amazing. Perfect for presentations.',
    date: '2024-05-16T13:00:00Z',
  },
  {
    id: 'rev_el_26',
    productId: 'prod_el_32', // Lenovo ThinkPad X1 Carbon (Gen 12)
    userName: 'CorporateClimber',
    rating: 5,
    comment: 'The quintessential business laptop. Keyboard is unmatched, and it\'s so light yet durable.',
    date: '2024-05-17T10:00:00Z',
  },
   {
    id: 'rev_el_27',
    productId: 'prod_el_16', // MacBook Pro 16" M3 Max Chip
    userName: '3DRenderWizard',
    rating: 5,
    comment: 'The M3 Max is an absolute monster for rendering and complex simulations. Worth every penny for professionals.',
    date: '2024-05-18T11:00:00Z',
  },
  {
    id: 'rev_el_28',
    productId: 'prod_el_20', // ASUS Vivobook Pro 16X OLED
    userName: 'DigitalArtist',
    rating: 4,
    comment: 'The 4K OLED display is fantastic for creative work. The DialPad is also quite useful for Adobe apps.',
    date: '2024-05-19T14:30:00Z',
  },
  {
    id: 'rev_el_29',
    productId: 'prod_el_23', // Xiaomi Book Air 13
    userName: 'TravelBlogger',
    rating: 4,
    comment: 'Incredibly thin and light, perfect for carrying around. The OLED screen is a nice bonus at this price.',
    date: '2024-05-20T09:15:00Z',
  },
  {
    id: 'rev_el_30',
    productId: 'prod_el_28', // HP Omen Transcend 14
    userName: 'StealthyGamer',
    rating: 5,
    comment: 'So light for a gaming laptop! The OLED screen is amazing for games. Doesn\'t scream "gamer" either.',
    date: '2024-05-21T17:00:00Z',
  },
  {
    id: 'rev_el_31',
    productId: 'prod_el_31', // Lenovo Legion Pro 7i (Gen 9)
    userName: 'HardcoreGamer',
    rating: 5,
    comment: 'This machine runs everything on ultra settings without breaking a sweat. Cooling is excellent.',
    date: '2024-05-22T12:00:00Z',
  },
  {
    id: 'rev_el_32',
    productId: 'prod_el_17', // iMac 24" M3 Chip
    userName: 'HomeOfficeHero',
    rating: 5,
    comment: 'Love the colorful design and the M3 chip is plenty fast for all my work. The display is beautiful.',
    date: '2024-05-23T10:45:00Z',
  },
  {
    id: 'rev_el_33',
    productId: 'prod_el_21', // ASUS TUF Gaming A15
    userName: 'BudgetGamer',
    rating: 4,
    comment: 'Solid gaming performance for the price. It\'s built like a tank, which is reassuring.',
    date: '2024-05-24T15:00:00Z',
  },
  {
    id: 'rev_el_34',
    productId: 'prod_el_25', // Xiaomi Gaming Laptop G Pro
    userName: 'CompetitivePlayer',
    rating: 4,
    comment: 'High refresh rate screen is great for competitive games. Performance is solid, but it can get a bit loud.',
    date: '2024-05-25T18:30:00Z',
  },
  {
    id: 'rev_el_35',
    productId: 'prod_el_27', // HP Envy x360 15
    userName: 'UniStudent',
    rating: 4,
    comment: 'Great all-rounder for university. Good for notes with the touchscreen and powerful enough for assignments.',
    date: '2024-05-26T11:00:00Z',
  },
  {
    id: 'rev_el_36',
    productId: 'prod_el_29', // HP Pavilion Aero 13
    userName: 'FrequentFlyer',
    rating: 5,
    comment: 'Can\'t believe how light this is! Makes traveling so much easier. Still has decent power for its size.',
    date: '2024-05-27T08:20:00Z',
  },
  {
    id: 'rev_el_37',
    productId: 'prod_el_33', // Lenovo IdeaPad Slim 5 (16-inch AMD)
    userName: 'FamilyUser',
    rating: 4,
    comment: 'Good value laptop for general family use. The large screen is nice for movies and browsing.',
    date: '2024-05-28T16:00:00Z',
  },
  // Reviews for new Audio products
  {
    id: 'rev_el_38',
    productId: 'prod_el_34', // Sony WH-1000XM5
    userName: 'AudiophileMike',
    rating: 5,
    comment: 'These are the best noise-canceling headphones, period. Sound is amazing, comfort is top-notch.',
    date: '2024-06-01T10:00:00Z',
  },
  {
    id: 'rev_el_39',
    productId: 'prod_el_34', // Sony WH-1000XM5
    userName: 'FrequentTraveler',
    rating: 5,
    comment: 'A must-have for flights. Blocks out all engine noise and the battery lasts forever.',
    date: '2024-06-02T11:30:00Z',
  },
  {
    id: 'rev_el_40',
    productId: 'prod_el_35', // Bose QuietComfort Ultra Headphones
    userName: 'BoseFanatic',
    rating: 5,
    comment: 'Bose does it again! The immersive audio is a game-changer and they are so comfortable.',
    date: '2024-06-03T14:15:00Z',
  },
  {
    id: 'rev_el_41',
    productId: 'prod_el_36', // Apple AirPods Max
    userName: 'AppleEcosystemUser',
    rating: 4,
    comment: 'Incredible sound and seamless integration with Apple devices. The price is steep, but the quality is there.',
    date: '2024-06-04T09:00:00Z',
  },
  {
    id: 'rev_el_42',
    productId: 'prod_el_37', // Sennheiser Momentum 4
    userName: 'MusicLoverSarah',
    rating: 5,
    comment: 'The battery life is insane! 60 hours is no joke. Sound quality is classic Sennheiser, warm and detailed.',
    date: '2024-06-05T16:45:00Z',
  },
  {
    id: 'rev_el_43',
    productId: 'prod_el_39', // Sony WF-1000XM5 Earbuds
    userName: 'CommuterPro',
    rating: 5,
    comment: 'Best earbuds for noise cancellation on my daily commute. Sound quality is fantastic for such small buds.',
    date: '2024-06-06T08:30:00Z',
  },
  {
    id: 'rev_el_44',
    productId: 'prod_el_40', // Bose QuietComfort Ultra Earbuds
    userName: 'GymRat',
    rating: 4,
    comment: 'Secure fit for workouts and the immersive audio makes my playlists sound amazing. ANC is top-tier.',
    date: '2024-06-07T17:00:00Z',
  },
  {
    id: 'rev_el_45',
    productId: 'prod_el_41', // Apple AirPods Pro (2nd Gen)
    userName: 'EverydayiOSUser',
    rating: 5,
    comment: 'The convenience and sound quality are unmatched in the Apple ecosystem. Touch controls are improved.',
    date: '2024-06-08T12:10:00Z',
  },
  {
    id: 'rev_el_46',
    productId: 'prod_el_44', // Anker Soundcore Liberty 4 NC
    userName: 'BudgetAudiophile',
    rating: 5,
    comment: 'Amazing value! The noise cancellation is surprisingly good for the price and the battery life is excellent.',
    date: '2024-06-09T15:00:00Z',
  },
  {
    id: 'rev_el_47',
    productId: 'prod_el_45', // Audio-Technica ATH-M50xBT2
    userName: 'StudioEngineer',
    rating: 4,
    comment: 'Great to have the M50x sound wirelessly. Solid build and long battery life for studio or casual listening.',
    date: '2024-06-10T10:20:00Z',
  },
  {
    id: 'rev_el_48',
    productId: 'prod_el_46', // Beats Studio Pro
    userName: 'BeatsFan',
    rating: 4,
    comment: 'Classic Beats sound with improved ANC and spatial audio. Lossless via USB-C is a nice touch.',
    date: '2024-06-11T13:30:00Z',
  },
  {
    id: 'rev_el_49',
    productId: 'prod_el_49', // Samsung Galaxy Buds2 Pro
    userName: 'SamsungUser',
    rating: 5,
    comment: 'Perfect companion for my Galaxy phone. The 24-bit audio sounds great and ANC is solid.',
    date: '2024-06-12T11:00:00Z',
  },
  {
    id: 'rev_el_50',
    productId: 'prod_el_50', // Google Pixel Buds Pro
    userName: 'AndroidDev',
    rating: 4,
    comment: 'Seamless integration with Pixel and Android. ANC is good and Google Assistant works flawlessly.',
    date: '2024-06-13T18:00:00Z',
  },
  {
    id: 'rev_el_51',
    productId: 'prod_el_51', // JBL Charge 5
    userName: 'PartyStarter',
    rating: 5,
    comment: 'This speaker is LOUD and the bass is punchy. Waterproof and can charge my phone, perfect for outdoors!',
    date: '2024-06-14T19:00:00Z',
  },
  {
    id: 'rev_el_52',
    productId: 'prod_el_52', // Bose SoundLink Flex
    userName: 'HikerDave',
    rating: 5,
    comment: 'Super rugged and sounds amazing for its size. Clips easily to my backpack. Bose quality shines through.',
    date: '2024-06-15T09:45:00Z',
  },
  {
    id: 'rev_el_53',
    productId: 'prod_el_53', // Sony LinkBuds S
    userName: 'ComfortSeeker',
    rating: 4,
    comment: 'So light and comfortable I forget I\'m wearing them! ANC is decent and they sound great.',
    date: '2024-06-16T14:00:00Z',
  },
  // Reviews for new Cameras & Drones
  {
    id: 'rev_el_54',
    productId: 'prod_el_54', // DJI Mavic 3 Pro
    userName: 'ProAerialVid',
    rating: 5,
    comment: 'The triple camera system is incredible. Hasselblad quality is unmatched. Worth the investment.',
    date: '2024-07-01T10:00:00Z',
  },
  {
    id: 'rev_el_55',
    productId: 'prod_el_55', // DJI Mini 4 Pro
    userName: 'TravelDronePilot',
    rating: 5,
    comment: 'Perfect travel drone! So small yet packed with features. Obstacle sensing is a lifesaver.',
    date: '2024-07-02T11:30:00Z',
  },
  {
    id: 'rev_el_56',
    productId: 'prod_el_58', // Sony Alpha 7 IV
    userName: 'HybridShooter',
    rating: 5,
    comment: 'Amazing for both photos and video. The autofocus is lightning fast and accurate.',
    date: '2024-07-03T14:15:00Z',
  },
  {
    id: 'rev_el_57',
    productId: 'prod_el_59', // Canon EOS R6 Mark II
    userName: 'EventPhotog',
    rating: 4,
    comment: 'Great all-rounder for events. Handles low light well and the AF is reliable.',
    date: '2024-07-04T09:00:00Z',
  },
  {
    id: 'rev_el_58',
    productId: 'prod_el_62', // GoPro HERO12 Black
    userName: 'Adventure Junkie',
    rating: 5,
    comment: 'HyperSmooth 6.0 is mind-blowing! Super stable footage no matter what I do. Battery life is better too.',
    date: '2024-07-05T16:45:00Z',
  },
  {
    id: 'rev_el_59',
    productId: 'prod_el_63', // Sony ZV-E10
    userName: 'VlogStar',
    rating: 4,
    comment: 'Great for vlogging! The flip screen and product showcase mode are super handy. Kit lens is decent to start.',
    date: '2024-07-06T08:30:00Z',
  },
  {
    id: 'rev_el_60',
    productId: 'prod_el_67', // DJI Osmo Action 4
    userName: 'UnderwaterExplorer',
    rating: 5,
    comment: 'Low light performance is noticeably better than previous action cams. 10-bit color is great for grading.',
    date: '2024-07-07T17:00:00Z',
  },
  {
    id: 'rev_el_61',
    productId: 'prod_el_69', // Insta360 X3
    userName: '360Creator',
    rating: 5,
    comment: 'So much fun to shoot with! The invisible selfie stick is magic and the app makes editing easy.',
    date: '2024-07-08T12:10:00Z',
  },
  {
    id: 'rev_el_62',
    productId: 'prod_el_73', // DJI RS 3 Mini
    userName: 'IndieFilmmaker',
    rating: 4,
    comment: 'Super lightweight gimbal that punches above its weight. Perfect for smaller mirrorless setups.',
    date: '2024-07-09T15:00:00Z',
  },
  {
    id: 'rev_el_63',
    productId: 'prod_el_56', // DJI Air 3
    userName: 'AerialHobbyist',
    rating: 5,
    comment: 'The dual cameras are very versatile. Great flight time and reliable transmission.',
    date: '2024-07-10T10:20:00Z',
  },
  {
    id: 'rev_el_64',
    productId: 'prod_el_60', // Nikon Z8
    userName: 'WildlifePhotogPro',
    rating: 5,
    comment: 'The Z8 is a beast for wildlife. Fast AF, incredible resolution, and robust build.',
    date: '2024-07-11T13:30:00Z',
  },
  {
    id: 'rev_el_65',
    productId: 'prod_el_61', // Fujifilm X-T5
    userName: 'StreetStyleSnapper',
    rating: 5,
    comment: 'Love the retro dials and Fuji colors. The high-res sensor captures amazing detail.',
    date: '2024-07-12T11:00:00Z',
  },
  // Reviews for new Wearable Technology
  {
    id: 'rev_el_66',
    productId: 'prod_el_74', // Apple Watch Series 9
    userName: 'AppleWatchFan',
    rating: 5,
    comment: 'The double tap gesture is surprisingly useful! Brighter screen is great outdoors.',
    date: '2024-08-01T09:00:00Z',
  },
  {
    id: 'rev_el_67',
    productId: 'prod_el_74', // Apple Watch Series 9
    userName: 'FitnessFreak',
    rating: 4,
    comment: 'Solid health tracking and love the ECG feature. Battery still needs daily charging for heavy use.',
    date: '2024-08-02T10:15:00Z',
  },
  {
    id: 'rev_el_68',
    productId: 'prod_el_75', // Samsung Galaxy Watch 6 Classic
    userName: 'GalaxyUser007',
    rating: 5,
    comment: 'The rotating bezel is back and it\'s amazing! Watch feels premium and works seamlessly with my Samsung phone.',
    date: '2024-08-03T11:30:00Z',
  },
  {
    id: 'rev_el_69',
    productId: 'prod_el_75', // Samsung Galaxy Watch 6 Classic
    userName: 'HealthNut',
    rating: 4,
    comment: 'BIA sensor is interesting. Sleep tracking is very detailed. Wish it had a bit more third-party app support.',
    date: '2024-08-04T12:45:00Z',
  },
  {
    id: 'rev_el_70',
    productId: 'prod_el_76', // Fitbit Charge 6
    userName: 'CasualTracker',
    rating: 5,
    comment: 'Perfect for my needs. Accurate tracking, Google Maps is handy, and the battery lasts for days!',
    date: '2024-08-05T14:00:00Z',
  },
  {
    id: 'rev_el_71',
    productId: 'prod_el_76', // Fitbit Charge 6
    userName: 'RunnerGirl',
    rating: 4,
    comment: 'Good GPS for runs. Heart rate on equipment is a cool feature. The screen is a bit small for some notifications.',
    date: '2024-08-06T15:15:00Z',
  },
  {
    id: 'rev_el_72',
    productId: 'prod_el_77', // Garmin Venu 3
    userName: 'SeriousAthlete',
    rating: 5,
    comment: 'Garmin\'s health and fitness metrics are unparalleled. Venu 3 has a beautiful AMOLED screen and great battery life.',
    date: '2024-08-07T16:30:00Z',
  },
  {
    id: 'rev_el_73',
    productId: 'prod_el_77', // Garmin Venu 3
    userName: 'SmartwatchExplorer',
    rating: 4,
    comment: 'Love the call functionality and the animated workouts. The Garmin ecosystem is robust.',
    date: '2024-08-08T17:45:00Z',
  },
  {
    id: 'rev_el_74',
    productId: 'prod_el_78', // Xiaomi Smart Band 8 Pro
    userName: 'BudgetWearableFan',
    rating: 5,
    comment: 'Incredible value for money! Large screen, GPS, and tons of features for a fraction of the price of others.',
    date: '2024-08-09T09:30:00Z',
  },
  {
    id: 'rev_el_75',
    productId: 'prod_el_78', // Xiaomi Smart Band 8 Pro
    userName: 'StyleConsciousUser',
    rating: 4,
    comment: 'Looks very sleek and the display is vibrant. Tracking is good for general fitness.',
    date: '2024-08-10T10:45:00Z',
  },
  {
    id: 'rev_el_76',
    productId: 'prod_el_79', // Google Pixel Watch 2
    userName: 'PixelPowerUser',
    rating: 4,
    comment: 'Much improved performance over the first gen. Fitbit integration is seamless. Battery is better but still needs a daily charge.',
    date: '2024-08-11T11:00:00Z',
  },
  {
    id: 'rev_el_77',
    productId: 'prod_el_80', // Amazfit Balance
    userName: 'ZenMaster',
    rating: 5,
    comment: 'The readiness score and AI coach are genuinely helpful. Great battery life and a beautiful display.',
    date: '2024-08-12T14:20:00Z',
  },
  {
    id: 'rev_el_78',
    productId: 'prod_el_81', // Huawei Watch GT 4
    userName: 'GlobalUser',
    rating: 4,
    comment: 'Stunning design and incredible battery life. Health tracking is comprehensive. App availability can be a limitation.',
    date: '2024-08-13T16:50:00Z',
  },
  // Reviews for new Smart Home Devices
  {
    id: 'rev_el_79',
    productId: 'prod_el_82', // Amazon Echo Dot (5th Gen)
    userName: 'AlexaFan',
    rating: 5,
    comment: 'Sound is much better on this gen! Alexa is responsive as always. Great value.',
    date: '2024-09-01T10:00:00Z',
  },
  {
    id: 'rev_el_80',
    productId: 'prod_el_82', // Amazon Echo Dot (5th Gen)
    userName: 'MusicLover',
    rating: 4,
    comment: 'Good for background music and controlling smart lights. Vocals are clear.',
    date: '2024-09-02T11:15:00Z',
  },
  {
    id: 'rev_el_81',
    productId: 'prod_el_83', // Google Nest Hub (2nd Gen)
    userName: 'GoogleHomeUser',
    rating: 5,
    comment: 'Perfect kitchen companion. Love the display for recipes and controlling my Nest devices. Sleep sensing is a cool bonus.',
    date: '2024-09-03T12:30:00Z',
  },
  {
    id: 'rev_el_82',
    productId: 'prod_el_84', // Philips Hue Starter Kit
    userName: 'LightingEnthusiast',
    rating: 5,
    comment: 'Hue lights are amazing! So many colors and scenes to choose from. Easy to set up and expand.',
    date: '2024-09-04T13:45:00Z',
  },
  {
    id: 'rev_el_83',
    productId: 'prod_el_85', // Ring Video Doorbell Pro 2
    userName: 'SecurityConscious',
    rating: 4,
    comment: 'Great video quality and the 3D motion detection works well. Subscription is a bit pricey but worth it for features.',
    date: '2024-09-05T15:00:00Z',
  },
  {
    id: 'rev_el_84',
    productId: 'prod_el_86', // Wyze Cam v3 Pro
    userName: 'BudgetSecurity',
    rating: 5,
    comment: 'Can\'t beat the value for a 2K camera with color night vision. Works surprisingly well.',
    date: '2024-09-06T16:15:00Z',
  },
  {
    id: 'rev_el_85',
    productId: 'prod_el_87', // TP-Link Kasa Smart Plug Mini
    userName: 'AutomationGeek',
    rating: 5,
    comment: 'These smart plugs are a staple in my smart home. Reliable and easy to use with Alexa.',
    date: '2024-09-07T17:30:00Z',
  },
  {
    id: 'rev_el_86',
    productId: 'prod_el_88', // Ecobee Smart Thermostat Premium
    userName: 'EnergySaver',
    rating: 5,
    comment: 'Love this thermostat! Already seeing savings on my energy bill. The SmartSensor is great for balancing temperature.',
    date: '2024-09-08T18:45:00Z',
  },
  {
    id: 'rev_el_87',
    productId: 'prod_el_89', // Arlo Pro 4 Spotlight Camera
    userName: 'HomeWatcher',
    rating: 4,
    comment: 'Good quality wire-free cameras. Spotlight is bright and deters well. Battery life is decent.',
    date: '2024-09-09T10:00:00Z',
  },
];

// Helper functions to get data
export const getProductById = (id: string): Product | undefined =>
  products.find(p => p.id === id);

export const getReviewsByProductId = (productId: string): Review[] =>
  reviews.filter(r => r.productId === productId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export const getProductsByCategoryId = (categoryId: string): Product[] =>
  products.filter(p => p.categoryId === categoryId);

export const getAllProducts = (): Product[] => products;

export const getAllCategories = (): Category[] => categories;
