
import type { Product, Category, Review } from '@/types';

export const categories: Category[] = [
  { id: 'cat_el_1', name: 'Smartphones & Accessories', slug: 'smartphones-accessories' },
  { id: 'cat_el_2', name: 'Laptops & Computers', slug: 'laptops-computers' },
  { id: 'cat_el_3', name: 'Audio & Headphones', slug: 'audio-headphones' },
  { id: 'cat_el_4', name: 'Cameras & Drones', slug: 'cameras-drones' },
  { id: 'cat_el_5', name: 'Gaming Consoles & Accessories', slug: 'gaming' },
  { id: 'cat_el_6', name: 'Wearable Technology', slug: 'wearables' },
  { id: 'cat_el_7', name: 'Smart Home Devices', slug: 'smart-home' },
];

export const products: Product[] = [
  {
    id: 'prod_el_1',
    name: 'AuraBeat Pro Wireless Headphones',
    description: 'Immerse yourself in pure audio bliss with AuraBeat Pro. Features active noise-cancellation, 30-hour battery life, and ultra-soft earcups for maximum comfort.',
    price: 249.99,
    imageUrl: 'https://picsum.photos/seed/auraheadphones/600/400',
    categoryId: 'cat_el_3',
    categoryName: 'Audio & Headphones',
    stock: 50,
    features: ['Active Noise Cancellation', 'Bluetooth 5.2', '30-hour battery life', 'Comfort-fit earcups', 'Crystal-clear microphone'],
    sku: 'AU-HP-789',
    brand: 'AuraAudio',
  },
  {
    id: 'prod_el_2',
    name: 'NovaPhone X2 Ultra Smartphone',
    description: 'Experience the future with NovaPhone X2 Ultra. Stunning 120Hz AMOLED display, powerful new-gen processor, and a revolutionary 108MP camera system.',
    price: 999.00,
    imageUrl: 'https://picsum.photos/seed/novaphone/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 35,
    features: ['6.8" 120Hz AMOLED Display', '12GB RAM', '256GB Storage', '108MP Triple Camera', '5G Connectivity'],
    sku: 'SM-NP-X2U',
    brand: 'NovaTech',
  },
  {
    id: 'prod_el_3',
    name: 'ZenithBook Air 14" Laptop',
    description: 'Ultra-portable and powerful, the ZenithBook Air is perfect for professionals and creatives on the go. Feather-light design with all-day battery life.',
    price: 1299.50,
    imageUrl: 'https://picsum.photos/seed/zenithbook/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 25,
    features: ['14" QHD+ Display', 'Latest Gen Intel Core i7', '16GB RAM', '1TB NVMe SSD', 'Backlit Keyboard', 'Thunderbolt 4'],
    sku: 'LT-ZB-A14',
    brand: 'ZenithComputers',
  },
  {
    id: 'prod_el_4',
    name: 'SkyHawk Pro Drone',
    description: 'Capture breathtaking aerial footage with the SkyHawk Pro Drone. Features 4K HDR video, 3-axis gimbal stabilization, and intelligent flight modes.',
    price: 799.00,
    imageUrl: 'https://picsum.photos/seed/skyhawkdrone/600/400',
    categoryId: 'cat_el_4',
    categoryName: 'Cameras & Drones',
    stock: 40,
    features: ['4K HDR Video @ 60fps', '30-min Flight Time', '5-mile Range', 'Obstacle Avoidance', 'Foldable Design'],
    sku: 'DR-SH-P4K',
    brand: 'AeroVision',
  },
  {
    id: 'prod_el_5',
    name: 'Vortex G1 Gaming Console',
    description: 'Enter the next generation of gaming with the Vortex G1. Experience lightning-fast load times, stunning 4K graphics, and a vast library of exclusive titles.',
    price: 499.99,
    imageUrl: 'https://picsum.photos/seed/vortexconsole/600/400',
    categoryId: 'cat_el_5',
    categoryName: 'Gaming Consoles & Accessories',
    stock: 60,
    features: ['8K Output Support', 'Custom NVMe SSD', 'Ray Tracing Technology', 'Backward Compatibility', 'Haptic Feedback Controller'],
    sku: 'GM-VG-001',
    brand: 'QuantumPlay',
  },
  {
    id: 'prod_el_6',
    name: 'ChronoFit Active Smartwatch',
    description: 'Stay connected and track your fitness goals with the ChronoFit Active. ECG, SpO2 monitoring, built-in GPS, and a vibrant always-on display.',
    price: 329.00,
    imageUrl: 'https://picsum.photos/seed/chronofitwatch/600/400',
    categoryId: 'cat_el_6',
    categoryName: 'Wearable Technology',
    stock: 70,
    features: ['ECG & SpO2 Monitor', 'Built-in GPS', 'Water Resistant (5ATM)', '1.4" AMOLED Display', '7-Day Battery Life'],
    sku: 'WT-CF-A05',
    brand: 'ChronoWear',
  },
  {
    id: 'prod_el_7',
    name: 'AuraHome Smart Hub Pro',
    description: 'Control your smart home devices with ease using the AuraHome Smart Hub Pro. Compatible with Zigbee, Z-Wave, and Wi-Fi devices.',
    price: 129.99,
    imageUrl: 'https://picsum.photos/seed/aurahomehub/600/400',
    categoryId: 'cat_el_7',
    categoryName: 'Smart Home Devices',
    stock: 55,
    features: ['Multi-protocol support', 'Voice assistant integration', 'Customizable automation scenes', 'Secure local control'],
    sku: 'SH-AH-PRO',
    brand: 'AuraHome',
  },
  {
    id: 'prod_el_8',
    name: 'StealthStrike Pro Gaming Mouse',
    description: 'Dominate the competition with the StealthStrike Pro Gaming Mouse. Ultra-lightweight design, 20K DPI optical sensor, and customizable RGB lighting.',
    price: 69.95,
    imageUrl: 'https://picsum.photos/seed/gamingmouse/600/400',
    categoryId: 'cat_el_5',
    categoryName: 'Gaming Consoles & Accessories',
    stock: 90,
    features: ['20,000 DPI Optical Sensor', 'Lightweight 60g Design', '8 Programmable Buttons', 'Customizable RGB Lighting'],
    sku: 'GM-MS-SSP',
    brand: 'RaptorGaming',
  },
  // New Smartphones
  {
    id: 'prod_el_9',
    name: 'Apple iPhone 15 Pro',
    description: 'The latest iPhone with Pro features, A17 Bionic chip, and advanced camera system.',
    price: 1199.00,
    imageUrl: 'https://picsum.photos/seed/iphone15pro/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 30,
    features: ['ProMotion Display', 'A17 Bionic Chip', '48MP Main Camera', 'Titanium Design', 'Action Button'],
    sku: 'SM-AP-IP15P',
    brand: 'Apple',
  },
  {
    id: 'prod_el_10',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Experience Galaxy AI with the S24 Ultra. Powerful performance, stunning display, and an incredible camera system with S Pen support.',
    price: 1299.00,
    imageUrl: 'https://picsum.photos/seed/galaxys24ultra/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 25,
    features: ['Dynamic AMOLED 2X', 'Snapdragon 8 Gen 3 for Galaxy', '200MP Main Camera', 'Built-in S Pen', 'Galaxy AI Features'],
    sku: 'SM-SS-S24U',
    brand: 'Samsung',
  },
  {
    id: 'prod_el_11',
    name: 'Xiaomi 14 Ultra',
    description: 'Co-engineered with Leica, the Xiaomi 14 Ultra offers a professional-grade photography experience in a smartphone.',
    price: 1099.00,
    imageUrl: 'https://picsum.photos/seed/xiaomi14ultra/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 40,
    features: ['Leica Quad Camera System', 'Snapdragon 8 Gen 3', '120Hz AMOLED Display', 'HyperCharge Technology', 'Ceramic Back'],
    sku: 'SM-XM-14U',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_12',
    name: 'Vivo X100 Pro',
    description: 'Capture stunning portraits and low-light shots with the Vivo X100 Pro, featuring ZEISS optics and advanced imaging technology.',
    price: 949.00,
    imageUrl: 'https://picsum.photos/seed/vivox100pro/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 35,
    features: ['ZEISS Co-engineered Camera', 'Dimensity 9300 Chipset', '120Hz LTPO AMOLED', '100W FlashCharge', 'V3 Imaging Chip'],
    sku: 'SM-VV-X100P',
    brand: 'Vivo',
  },
  {
    id: 'prod_el_13',
    name: 'Realme GT 5 Pro',
    description: 'Flagship performance at a competitive price. The Realme GT 5 Pro offers a powerful processor, a bright display, and fast charging.',
    price: 799.00,
    imageUrl: 'https://picsum.photos/seed/realmegt5pro/600/400',
    categoryId: 'cat_el_1',
    categoryName: 'Smartphones & Accessories',
    stock: 50,
    features: ['Snapdragon 8 Gen 3', '144Hz AMOLED Display', 'Sony IMX890 OIS Camera', '240W SuperVOOC Charge', 'Stainless Steel Vapor Cooling'],
    sku: 'SM-RM-GT5P',
    brand: 'Realme',
  },
  // New Laptops
  {
    id: 'prod_el_14',
    name: 'MacBook Air 13" M3 Chip',
    description: 'The incredibly thin and light MacBook Air, now supercharged by the M3 chip. Delivers powerhouse performance and up to 18 hours of battery life.',
    price: 1099.00,
    imageUrl: 'https://picsum.photos/seed/macbookair13m3/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 45,
    features: ['Apple M3 Chip', '13.6-inch Liquid Retina Display', '8GB Unified Memory', '256GB SSD Storage', 'Up to 18 hours battery life', 'Silent, fanless design'],
    sku: 'LT-AP-MBA13M3',
    brand: 'Apple',
  },
  {
    id: 'prod_el_15',
    name: 'MacBook Pro 14" M3 Pro Chip',
    description: 'The MacBook Pro 14” with the M3 Pro chip offers game-changing performance for demanding workflows. Features a stunning Liquid Retina XDR display.',
    price: 1999.00,
    imageUrl: 'https://picsum.photos/seed/macbookpro14m3pro/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 30,
    features: ['Apple M3 Pro Chip', '14.2-inch Liquid Retina XDR Display', '18GB Unified Memory', '512GB SSD Storage', 'ProMotion technology', 'Advanced thermal system'],
    sku: 'LT-AP-MBP14M3P',
    brand: 'Apple',
  },
  {
    id: 'prod_el_16',
    name: 'MacBook Pro 16" M3 Max Chip',
    description: 'The ultimate pro laptop, the MacBook Pro 16” with M3 Max chip takes performance to new heights for the most extreme workflows.',
    price: 3499.00,
    imageUrl: 'https://picsum.photos/seed/macbookpro16m3max/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 20,
    features: ['Apple M3 Max Chip', '16.2-inch Liquid Retina XDR Display', '36GB Unified Memory', '1TB SSD Storage', 'Enhanced media engine', 'Studio-quality mics'],
    sku: 'LT-AP-MBP16M3MAX',
    brand: 'Apple',
  },
  {
    id: 'prod_el_17',
    name: 'iMac 24" M3 Chip',
    description: 'The all-in-one desktop, transformed by the M3 chip. Features a stunning 24-inch 4.5K Retina display in a remarkably thin design.',
    price: 1299.00,
    imageUrl: 'https://picsum.photos/seed/imac24m3/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 25,
    features: ['Apple M3 Chip', '24-inch 4.5K Retina Display', '8GB Unified Memory', '256GB SSD Storage', '1080p FaceTime HD camera', 'Magic Keyboard with Touch ID'],
    sku: 'DT-AP-IMAC24M3',
    brand: 'Apple',
  },
  {
    id: 'prod_el_18',
    name: 'ASUS ROG Zephyrus G14 (2024)',
    description: 'The ROG Zephyrus G14 is a highly portable gaming powerhouse with a stunning Nebula Display and the latest AMD Ryzen AI processors.',
    price: 1599.99,
    imageUrl: 'https://picsum.photos/seed/asusrogzephyrusg14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 35,
    features: ['AMD Ryzen 9 8000 Series with AI', 'NVIDIA GeForce RTX 4070 Laptop GPU', '14-inch QHD+ 165Hz Nebula Display', '16GB DDR5 RAM', '1TB PCIe 4.0 SSD', 'AniMe Matrix™ display'],
    sku: 'LT-AS-ROGZG14',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_19',
    name: 'ASUS Zenbook Duo (2024)',
    description: 'Experience ultimate productivity with the revolutionary ASUS Zenbook Duo, featuring two full-size OLED touchscreens.',
    price: 1999.99,
    imageUrl: 'https://picsum.photos/seed/asuszenbookduo/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 22,
    features: ['Intel Core Ultra 9 Processor', 'Dual 14-inch 3K OLED Touchscreens', '32GB LPDDR5X RAM', '1TB PCIe 4.0 SSD', 'Detachable full-size keyboard', 'AI-powered features'],
    sku: 'LT-AS-ZBDUO24',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_20',
    name: 'ASUS Vivobook Pro 16X OLED',
    description: 'Unleash your creative power with the Vivobook Pro 16X OLED, featuring a stunning 4K OLED display and high-performance components.',
    price: 1799.00,
    imageUrl: 'https://picsum.photos/seed/asusvivobookpro16x/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 28,
    features: ['Intel Core i9 H-Series Processor', 'NVIDIA GeForce RTX 4060 Laptop GPU', '16-inch 4K OLED Display', '32GB DDR5 RAM', '1TB PCIe SSD', 'ASUS DialPad'],
    sku: 'LT-AS-VBPRO16X',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_21',
    name: 'ASUS TUF Gaming A15',
    description: 'The ASUS TUF Gaming A15 is a durable gaming laptop that delivers reliable performance for all your favorite titles.',
    price: 1199.00,
    imageUrl: 'https://picsum.photos/seed/asustufgaminga15/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 40,
    features: ['AMD Ryzen 7 7000 Series Processor', 'NVIDIA GeForce RTX 4050 Laptop GPU', '15.6-inch FHD 144Hz Display', '16GB DDR5 RAM', '512GB PCIe SSD', 'Military-grade durability'],
    sku: 'LT-AS-TUFA15',
    brand: 'ASUS',
  },
  {
    id: 'prod_el_22',
    name: 'Xiaomi Book Pro 14 (2024)',
    description: 'The Xiaomi Book Pro 14 offers a sleek design, a high-resolution display, and powerful performance for professionals.',
    price: 999.00,
    imageUrl: 'https://picsum.photos/seed/xiaomibookpro14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 33,
    features: ['Intel Core Ultra 7 Processor', 'Intel Arc Graphics', '14-inch 2.8K OLED Display', '16GB LPDDR5 RAM', '1TB PCIe 4.0 SSD', 'CNC unibody design'],
    sku: 'LT-XM-BPRO14',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_23',
    name: 'Xiaomi Book Air 13',
    description: 'An ultra-thin and lightweight laptop from Xiaomi, perfect for portability without sacrificing essential performance.',
    price: 749.00,
    imageUrl: 'https://picsum.photos/seed/xiaomibookair13/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 42,
    features: ['Intel Core i5 U-Series Processor', 'Intel Iris Xe Graphics', '13.3-inch FHD OLED Display', '16GB RAM', '512GB SSD', 'Slim and light chassis'],
    sku: 'LT-XM-BAIR13',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_24',
    name: 'RedmiBook Pro 15 (2024)',
    description: 'The RedmiBook Pro 15 balances performance and value, featuring a high-refresh-rate display and capable hardware.',
    price: 899.00,
    imageUrl: 'https://picsum.photos/seed/redmibookpro15/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 38,
    features: ['AMD Ryzen 7 7840HS Processor', 'Integrated AMD Radeon Graphics', '15.6-inch 3.2K 120Hz Display', '16GB DDR5 RAM', '512GB PCIe SSD', 'Full-metal body'],
    sku: 'LT-XM-RMBP15',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_25',
    name: 'Xiaomi Gaming Laptop G Pro',
    description: 'A performance-focused gaming laptop from Xiaomi with aggressive styling and powerful cooling.',
    price: 1399.00,
    imageUrl: 'https://picsum.photos/seed/xiaomigaminggpro/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 25,
    features: ['Intel Core i7 H-Series Processor', 'NVIDIA GeForce RTX 4060 Laptop GPU', '16-inch QHD 240Hz Display', '16GB DDR5 RAM', '1TB PCIe SSD', 'Advanced cooling system'],
    sku: 'LT-XM-GLGPRO',
    brand: 'Xiaomi',
  },
  {
    id: 'prod_el_26',
    name: 'HP Spectre x360 14 (2024)',
    description: 'The HP Spectre x360 14 is a premium 2-in-1 laptop with a stunning OLED display, versatile design, and AI-enhanced features.',
    price: 1649.99,
    imageUrl: 'https://picsum.photos/seed/hpspectrex36014/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 30,
    features: ['Intel Core Ultra 7 Processor', 'Intel Arc Graphics', '14-inch 2.8K OLED Touchscreen', '16GB RAM', '1TB SSD', 'HP Stylus included', 'AI NPU'],
    sku: 'LT-HP-SPX36014',
    brand: 'HP',
  },
  {
    id: 'prod_el_27',
    name: 'HP Envy x360 15',
    description: 'A versatile and stylish 2-in-1 laptop, the HP Envy x360 15 is perfect for both work and creativity.',
    price: 999.99,
    imageUrl: 'https://picsum.photos/seed/hpenvyx36015/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 36,
    features: ['AMD Ryzen 7 Processor', 'AMD Radeon Graphics', '15.6-inch FHD IPS Touchscreen', '16GB RAM', '512GB SSD', 'Bang & Olufsen Audio'],
    sku: 'LT-HP-ENVX36015',
    brand: 'HP',
  },
  {
    id: 'prod_el_28',
    name: 'HP Omen Transcend 14',
    description: 'The HP Omen Transcend 14 is one of the lightest 14-inch gaming laptops, featuring a vibrant OLED screen and powerful performance.',
    price: 1699.99,
    imageUrl: 'https://picsum.photos/seed/hpomentranscend14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 20,
    features: ['Intel Core Ultra 9 Processor', 'NVIDIA GeForce RTX 4070 Laptop GPU', '14-inch 2.8K OLED 120Hz Display', '32GB RAM', '1TB SSD', 'HyperX Audio'],
    sku: 'LT-HP-OMTR14',
    brand: 'HP',
  },
  {
    id: 'prod_el_29',
    name: 'HP Pavilion Aero 13',
    description: 'The HP Pavilion Aero 13 is incredibly lightweight and offers excellent performance for everyday tasks and portability.',
    price: 799.99,
    imageUrl: 'https://picsum.photos/seed/hppavilionaero13/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 45,
    features: ['AMD Ryzen 5 Processor', 'AMD Radeon Graphics', '13.3-inch WUXGA Display', '16GB RAM', '512GB SSD', 'Weighs less than 1kg'],
    sku: 'LT-HP-PAVAERO13',
    brand: 'HP',
  },
  {
    id: 'prod_el_30',
    name: 'Lenovo Yoga 9i (14-inch, Gen 9)',
    description: 'The Lenovo Yoga 9i combines stunning design with powerful performance and innovative features, including a rotating soundbar.',
    price: 1799.00,
    imageUrl: 'https://picsum.photos/seed/lenovoyoga9i14/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 28,
    features: ['Intel Core Ultra 7 Processor', 'Intel Arc Graphics', '14-inch 4K OLED PureSight Touch Display', '16GB RAM', '1TB SSD', 'Bowers & Wilkins rotating soundbar'],
    sku: 'LT-LN-Y9I14G9',
    brand: 'Lenovo',
  },
  {
    id: 'prod_el_31',
    name: 'Lenovo Legion Pro 7i (Gen 9)',
    description: 'Experience top-tier gaming performance with the Lenovo Legion Pro 7i, featuring AI-tuned power and advanced cooling.',
    price: 2499.00,
    imageUrl: 'https://picsum.photos/seed/lenovolegionpro7i/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 18,
    features: ['Intel Core i9 HX-Series Processor', 'NVIDIA GeForce RTX 4080 Laptop GPU', '16-inch WQXGA 240Hz Display', '32GB DDR5 RAM', '1TB PCIe SSD', 'Legion ColdFront 5.0 cooling'],
    sku: 'LT-LN-LPRO7IG9',
    brand: 'Lenovo',
  },
  {
    id: 'prod_el_32',
    name: 'Lenovo ThinkPad X1 Carbon (Gen 12)',
    description: 'The iconic ThinkPad X1 Carbon, now even lighter and more powerful, designed for ultimate business productivity and durability.',
    price: 2100.00,
    imageUrl: 'https://picsum.photos/seed/lenovothinkpadx1c12/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 32,
    features: ['Intel Core Ultra Processors with vPro', 'Intel Arc Graphics', '14-inch Display options up to OLED', 'Up to 64GB RAM', 'Up to 2TB SSD', 'Legendary ThinkPad keyboard'],
    sku: 'LT-LN-TPX1C12',
    brand: 'Lenovo',
  },
  {
    id: 'prod_el_33',
    name: 'Lenovo IdeaPad Slim 5 (16-inch AMD)',
    description: 'A stylish and capable everyday laptop, the IdeaPad Slim 5 offers a large display and reliable performance for work and entertainment.',
    price: 799.00,
    imageUrl: 'https://picsum.photos/seed/lenovoideapadslim5/600/400',
    categoryId: 'cat_el_2',
    categoryName: 'Laptops & Computers',
    stock: 40,
    features: ['AMD Ryzen 7 U-Series Processor', 'AMD Radeon Graphics', '16-inch WUXGA IPS Display', '16GB RAM', '512GB SSD', 'Privacy Shutter'],
    sku: 'LT-LN-IPSLIM5A',
    brand: 'Lenovo',
  },
];

export const reviews: Review[] = [
  {
    id: 'rev_el_1',
    productId: 'prod_el_1', // AuraBeat Pro Wireless Headphones
    userName: 'Alice Wonderland',
    rating: 5,
    comment: 'Absolutely love these headphones! The noise cancellation is top-notch and they are so comfortable for long listening sessions.',
    date: '2024-03-15T10:00:00Z',
  },
  {
    id: 'rev_el_2',
    productId: 'prod_el_1', // AuraBeat Pro Wireless Headphones
    userName: 'Bob The Builder',
    rating: 4,
    comment: 'Great sound quality and ANC. The battery life is fantastic. A bit pricey, but worth it.',
    date: '2024-03-20T14:30:00Z',
  },
  {
    id: 'rev_el_3',
    productId: 'prod_el_2', // NovaPhone X2 Ultra Smartphone
    userName: 'Charlie R.',
    rating: 5,
    comment: 'This phone is a beast! Camera is incredible, and it handles everything I throw at it. Display is gorgeous.',
    date: '2024-04-05T09:15:00Z',
  },
  {
    id: 'rev_el_4',
    productId: 'prod_el_3', // ZenithBook Air 14" Laptop
    userName: 'Diana P.',
    rating: 4,
    comment: 'Super light and portable, battery lasts all day. Keyboard is comfortable for typing. Screen is crisp.',
    date: '2024-04-01T11:00:00Z',
  },
  {
    id: 'rev_el_5',
    productId: 'prod_el_6', // ChronoFit Active Smartwatch
    userName: 'Eddie M.',
    rating: 5,
    comment: 'Best smartwatch I\'ve owned. Tracks everything accurately and the screen is very bright outdoors.',
    date: '2024-03-25T16:45:00Z',
  },
  {
    id: 'rev_el_6',
    productId: 'prod_el_4', // SkyHawk Pro Drone
    userName: 'Fiona G.',
    rating: 5,
    comment: 'Incredible drone for the price. Stable flight and amazing video quality. Easy to learn for beginners too!',
    date: '2024-02-28T07:30:00Z',
  },
   {
    id: 'rev_el_7',
    productId: 'prod_el_5', // Vortex G1 Gaming Console
    userName: 'GamerGuyX',
    rating: 5,
    comment: 'Next-gen is finally here! Load times are insane and the graphics are breathtaking. Controller feels great.',
    date: '2024-04-10T18:00:00Z',
  },
  {
    id: 'rev_el_8',
    productId: 'prod_el_7', // AuraHome Smart Hub Pro
    userName: 'SmartHomeFan',
    rating: 4,
    comment: 'Connects all my devices seamlessly. App is pretty good, but could use a few more integrations.',
    date: '2024-03-01T12:00:00Z',
  },
  // Reviews for new smartphones
  {
    id: 'rev_el_9',
    productId: 'prod_el_9', // Apple iPhone 15 Pro
    userName: 'TechGuru101',
    rating: 5,
    comment: 'The Action Button is a game changer! Performance is buttery smooth.',
    date: '2024-05-01T10:00:00Z',
  },
  {
    id: 'rev_el_10',
    productId: 'prod_el_9', // Apple iPhone 15 Pro
    userName: 'AppleFanatic',
    rating: 4,
    comment: 'Great phone, but battery life could be a bit better for heavy users.',
    date: '2024-05-03T11:00:00Z',
  },
  {
    id: 'rev_el_11',
    productId: 'prod_el_10', // Samsung Galaxy S24 Ultra
    userName: 'AndroidCentral',
    rating: 5,
    comment: 'Galaxy AI is surprisingly useful. The camera zoom is incredible!',
    date: '2024-05-02T14:00:00Z',
  },
  {
    id: 'rev_el_12',
    productId: 'prod_el_10', // Samsung Galaxy S24 Ultra
    userName: 'PenMaster',
    rating: 5,
    comment: 'Love the S Pen integration. This is the ultimate productivity phone.',
    date: '2024-05-04T15:00:00Z',
  },
  {
    id: 'rev_el_13',
    productId: 'prod_el_11', // Xiaomi 14 Ultra
    userName: 'PhotoPro',
    rating: 5,
    comment: 'Leica partnership really shines. The camera details are stunning.',
    date: '2024-04-28T10:30:00Z',
  },
  {
    id: 'rev_el_14',
    productId: 'prod_el_11', // Xiaomi 14 Ultra
    userName: 'ValueSeeker',
    rating: 4,
    comment: 'Flagship specs without the absolute top-tier price. Great deal.',
    date: '2024-04-30T12:00:00Z',
  },
  {
    id: 'rev_el_15',
    productId: 'prod_el_12', // Vivo X100 Pro
    userName: 'PortraitFan',
    rating: 5,
    comment: 'ZEISS portraits are unmatched. Amazing low-light performance.',
    date: '2024-05-05T09:00:00Z',
  },
  {
    id: 'rev_el_16',
    productId: 'prod_el_12', // Vivo X100 Pro
    userName: 'SpeedyCharge',
    rating: 4,
    comment: 'Super fast charging is a lifesaver. Display is also beautiful.',
    date: '2024-05-06T13:15:00Z',
  },
  {
    id: 'rev_el_17',
    productId: 'prod_el_13', // Realme GT 5 Pro
    userName: 'GamerMobile',
    rating: 5,
    comment: 'Handles all games smoothly. The 144Hz display is a treat.',
    date: '2024-04-25T17:00:00Z',
  },
  {
    id: 'rev_el_18',
    productId: 'prod_el_13', // Realme GT 5 Pro
    userName: 'BudgetKing',
    rating: 4,
    comment: 'Incredible value for the performance you get. Solid all-rounder.',
    date: '2024-04-27T19:30:00Z',
  },
  // Reviews for new laptops
  {
    id: 'rev_el_19',
    productId: 'prod_el_14', // MacBook Air 13" M3 Chip
    userName: 'StudentLife',
    rating: 5,
    comment: 'Perfect for college! So light and the M3 chip is surprisingly powerful. Battery lasts forever.',
    date: '2024-05-10T08:00:00Z',
  },
  {
    id: 'rev_el_20',
    productId: 'prod_el_15', // MacBook Pro 14" M3 Pro Chip
    userName: 'VideoEditorPro',
    rating: 5,
    comment: 'M3 Pro chews through 4K video edits. The XDR display is a dream for color accuracy.',
    date: '2024-05-11T10:30:00Z',
  },
  {
    id: 'rev_el_21',
    productId: 'prod_el_18', // ASUS ROG Zephyrus G14
    userName: 'RoadWarriorGamer',
    rating: 5,
    comment: 'Finally, a portable gaming laptop that doesn\'t compromise on power. The Nebula display is stunning!',
    date: '2024-05-12T14:15:00Z',
  },
  {
    id: 'rev_el_22',
    productId: 'prod_el_19', // ASUS Zenbook Duo (2024)
    userName: 'MultitaskMaster',
    rating: 4,
    comment: 'The dual screens are a productivity game-changer. A bit of a learning curve but so worth it.',
    date: '2024-05-13T09:00:00Z',
  },
  {
    id: 'rev_el_23',
    productId: 'prod_el_22', // Xiaomi Book Pro 14 (2024)
    userName: 'SleekXiaomiFan',
    rating: 4,
    comment: 'Beautiful design and the OLED screen is vibrant. Great performance for the price.',
    date: '2024-05-14T11:45:00Z',
  },
  {
    id: 'rev_el_24',
    productId: 'prod_el_26', // HP Spectre x360 14 (2024)
    userName: 'CreativeConvert',
    rating: 5,
    comment: 'This 2-in-1 is pure luxury. The OLED touch display is responsive and the AI features are a nice touch.',
    date: '2024-05-15T16:20:00Z',
  },
  {
    id: 'rev_el_25',
    productId: 'prod_el_30', // Lenovo Yoga 9i (14-inch, Gen 9)
    userName: 'AudiophileExec',
    rating: 5,
    comment: 'The rotating soundbar is incredible! Laptop itself is powerful and looks amazing. Perfect for presentations.',
    date: '2024-05-16T13:00:00Z',
  },
  {
    id: 'rev_el_26',
    productId: 'prod_el_32', // Lenovo ThinkPad X1 Carbon (Gen 12)
    userName: 'CorporateClimber',
    rating: 5,
    comment: 'The quintessential business laptop. Keyboard is unmatched, and it\'s so light yet durable.',
    date: '2024-05-17T10:00:00Z',
  },
   {
    id: 'rev_el_27',
    productId: 'prod_el_16', // MacBook Pro 16" M3 Max Chip
    userName: '3DRenderWizard',
    rating: 5,
    comment: 'The M3 Max is an absolute monster for rendering and complex simulations. Worth every penny for professionals.',
    date: '2024-05-18T11:00:00Z',
  },
  {
    id: 'rev_el_28',
    productId: 'prod_el_20', // ASUS Vivobook Pro 16X OLED
    userName: 'DigitalArtist',
    rating: 4,
    comment: 'The 4K OLED display is fantastic for creative work. The DialPad is also quite useful for Adobe apps.',
    date: '2024-05-19T14:30:00Z',
  },
  {
    id: 'rev_el_29',
    productId: 'prod_el_23', // Xiaomi Book Air 13
    userName: 'TravelBlogger',
    rating: 4,
    comment: 'Incredibly thin and light, perfect for carrying around. The OLED screen is a nice bonus at this price.',
    date: '2024-05-20T09:15:00Z',
  },
  {
    id: 'rev_el_30',
    productId: 'prod_el_28', // HP Omen Transcend 14
    userName: 'StealthyGamer',
    rating: 5,
    comment: 'So light for a gaming laptop! The OLED screen is amazing for games. Doesn\'t scream "gamer" either.',
    date: '2024-05-21T17:00:00Z',
  },
  {
    id: 'rev_el_31',
    productId: 'prod_el_31', // Lenovo Legion Pro 7i (Gen 9)
    userName: 'HardcoreGamer',
    rating: 5,
    comment: 'This machine runs everything on ultra settings without breaking a sweat. Cooling is excellent.',
    date: '2024-05-22T12:00:00Z',
  },
  {
    id: 'rev_el_32',
    productId: 'prod_el_17', // iMac 24" M3 Chip
    userName: 'HomeOfficeHero',
    rating: 5,
    comment: 'Love the colorful design and the M3 chip is plenty fast for all my work. The display is beautiful.',
    date: '2024-05-23T10:45:00Z',
  },
  {
    id: 'rev_el_33',
    productId: 'prod_el_21', // ASUS TUF Gaming A15
    userName: 'BudgetGamer',
    rating: 4,
    comment: 'Solid gaming performance for the price. It\'s built like a tank, which is reassuring.',
    date: '2024-05-24T15:00:00Z',
  },
  {
    id: 'rev_el_34',
    productId: 'prod_el_25', // Xiaomi Gaming Laptop G Pro
    userName: 'CompetitivePlayer',
    rating: 4,
    comment: 'High refresh rate screen is great for competitive games. Performance is solid, but it can get a bit loud.',
    date: '2024-05-25T18:30:00Z',
  },
  {
    id: 'rev_el_35',
    productId: 'prod_el_27', // HP Envy x360 15
    userName: 'UniStudent',
    rating: 4,
    comment: 'Great all-rounder for university. Good for notes with the touchscreen and powerful enough for assignments.',
    date: '2024-05-26T11:00:00Z',
  },
  {
    id: 'rev_el_36',
    productId: 'prod_el_29', // HP Pavilion Aero 13
    userName: 'FrequentFlyer',
    rating: 5,
    comment: 'Can\'t believe how light this is! Makes traveling so much easier. Still has decent power for its size.',
    date: '2024-05-27T08:20:00Z',
  },
  {
    id: 'rev_el_37',
    productId: 'prod_el_33', // Lenovo IdeaPad Slim 5 (16-inch AMD)
    userName: 'FamilyUser',
    rating: 4,
    comment: 'Good value laptop for general family use. The large screen is nice for movies and browsing.',
    date: '2024-05-28T16:00:00Z',
  },
];

// Helper functions to get data
export const getProductById = (id: string): Product | undefined =>
  products.find(p => p.id === id);

export const getReviewsByProductId = (productId: string): Review[] =>
  reviews.filter(r => r.productId === productId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export const getProductsByCategoryId = (categoryId: string): Product[] =>
  products.filter(p => p.categoryId === categoryId);

export const getAllProducts = (): Product[] => products;

export const getAllCategories = (): Category[] => categories;
