
"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

export type Language = 'ru' | 'en' | 'kk';

type Translations = {
  [key: string]: string | { one: string; few: string; many: string };
};

type Dictionaries = {
  [lang in Language]: Translations;
};

const dictionaries: Dictionaries = {
  ru: {
    'app.name': 'TechShop',
    'nav.catalog': 'Каталог',
    'nav.menu_open_aria': 'Открыть меню',
    'nav.cart': 'Корзина',
    'nav.wishlist': 'Избранное',
    'nav.profile': 'Профиль',
    'nav.login': 'Вход',
    'footer.copyright': '© {year} TechShop. Все права защищены.',
    'footer.powered_by': 'Работает на Next.js и ShadCN UI',

    'search.placeholder': 'Поиск товаров...',
    'search.submit_aria_label': 'Найти',
    'search.loading': 'Загрузка...',
    'search.no_results_for_query': 'Товары по запросу "{query}" не найдены.',
    'search.show_all_results_for_query': 'Показать все результаты для "{query}"',
    'search.title': 'Поиск товаров',
    'search.enter_query_placeholder': 'Введите поисковый запрос в строке поиска выше, чтобы найти интересующие вас товары.',
    'search.results_title': 'Результаты поиска: "{query}"',
    'search.found_count': 'Найдено: {count} {noun}',

    'product.brand': 'Бренд',
    'product.rating': 'Рейтинг',
    'product.reviews_count_parentheses': '({count} {noun})',
    'product.characteristics': 'Характеристики',
    'product.sku': 'Артикул',
    'product.availability': 'Наличие',
    'product.availability_available': '{stock} {noun} доступно',
    'product.availability_out_of_stock': 'Нет в наличии',
    'product.add_to_cart': 'В корзину',
    'product.go_to_product': 'К товару',
    'product.delivery_estimate': 'Примерный срок доставки: 2-5 дней.',
    'product.payment_methods_note': 'Доступные способы оплаты: Kaspi, Visa, MasterCard.',
    'product.add_to_wishlist_aria': 'Добавить в избранное',
    'product.remove_from_wishlist_aria': 'Удалить из избранного',
    'product.toast_added_to_cart_title': 'Добавлено в корзину',
    'product.toast_added_to_cart_desc': '{name} добавлен в вашу корзину ({count} шт).',
    'product.toast_added_to_wishlist_title': 'Добавлено в избранное',
    'product.toast_added_to_wishlist_desc': '{name} добавлен в ваше избранное.',
    'product.toast_removed_from_wishlist_title': 'Удалено из избранного',
    'product.toast_removed_from_wishlist_desc': '{name} удален из вашего избранного.',
    'product.quantity_aria': 'Количество',
    'product.decrease_quantity_aria': 'Уменьшить количество',
    'product.increase_quantity_aria': 'Увеличить количество',
    'product.page_title': 'Товары',
    'product.page_description': 'Ознакомьтесь со всеми нашими товарами в TechShop. Фильтруйте по цене, бренду и другим характеристикам.',
    'product.all_products_title': 'Все товары',
    'product.category_not_found_title': 'Категория не найдена',
    'product.search_results_in_category_title': 'Результаты поиска по запросу "{query}" в категории "{categoryName}"',
    'product.no_products_found_generic': 'Товары не найдены.',
    'product.no_products_in_category': 'Товары в категории "{categoryName}" не найдены.',
    'product.product_not_found_title': 'Товар не найден',


    'filter.sidebar_title': 'Фильтры',
    'filter.reset_all': 'Сбросить все',
    'filter.price_label': 'Цена',
    'filter.brand_label': 'Бренд',
    'filter.color_label': 'Цвет',
    'filter.min_price_aria': 'Минимальная цена',
    'filter.max_price_aria': 'Максимальная цена',
    'filter.applied_filters': 'Примененные фильтры:',
    'filter.remove_filter_aria': 'Удалить фильтр {label}',
    'filter.price_range_label': 'Цена: {minPrice} - {maxPrice} ₸',
    'filter.brand_filter_label': 'Бренд: {brand}',
    'filter.color_filter_label': 'Цвет: {color}',
    'filter.mobile_filters_button': 'Фильтры',
    'filter.category_filter_title': 'Фильтр по категориям',
    'filter.select_category_placeholder': 'Выберите категорию',
    'filter.all_categories': 'Все категории',


    'sort.label': 'Сортировать по:',
    'sort.placeholder': 'Выберите сортировку',
    'sort.popularity': 'Популярности',
    'sort.price_asc': 'Цена: по возрастанию',
    'sort.price_desc': 'Цена: по убыванию',
    'sort.newest': 'Новизне',
    'sort.name_asc': 'Название: А-Я',
    'sort.name_desc': 'Название: Я-А',

    'reviews.title': 'Отзывы покупателей ({count} {noun})',
    'reviews.average_rating': 'Средняя оценка: {rating} из 5',
    'reviews.no_reviews': 'Отзывов на этот товар пока нет.',
    'reviews.leave_review_title': 'Оставить отзыв',
    'reviews.leave_review_description': 'Поделитесь своим мнением о товаре с другими покупателями.',
    'reviews.your_rating_label': 'Ваша оценка',
    'reviews.your_comment_label': 'Ваш отзыв',
    'reviews.comment_placeholder': 'Напишите, что вы думаете о товаре...',
    'reviews.submit_button': 'Оставить отзыв',
    'reviews.submitting_button': 'Отправка...',
    'reviews.toast_submitted_title': 'Отзыв добавлен!',
    'reviews.toast_submitted_desc': 'Спасибо за ваш отзыв.',
    'reviews.toast_error_title': 'Ошибка',
    'reviews.toast_error_desc': 'Не удалось добавить отзыв. Пожалуйста, попробуйте еще раз.',
    'reviews.toast_auth_error_desc': 'Вы должны быть авторизованы, чтобы оставить отзыв.',
    'reviews.login_prompt_title': 'Хотите оставить отзыв?',
    'reviews.login_prompt_text_before_links': '',
    'reviews.login_prompt_login_link': 'Войдите',
    'reviews.login_prompt_text_between_links': ' или ',
    'reviews.login_prompt_register_link': 'зарегистрируйтесь',
    'reviews.login_prompt_text_after_links': ', чтобы поделиться своим мнением о товаре.',
    'reviews.purchase_required_title': 'Поделитесь мнением',
    'reviews.purchase_required_text': 'Вы сможете оставить отзыв на этот товар после его покупки.',
    'reviews.already_reviewed_title': 'Спасибо за ваш отзыв!',
    'reviews.already_reviewed_text': 'Вы уже оставили отзыв на этот товар.',
    'reviews.loading_auth_status': 'Проверка статуса авторизации...',
    'reviews.rating_required': 'Пожалуйста, поставьте оценку.',
    'reviews.comment_min_length': 'Отзыв должен содержать не менее 10 символов.',
    'reviews.comment_max_length': 'Отзыв не должен превышать 1000 символов.',
    'user.anonymous': 'Анонимный пользователь',


    'cart.page_title': 'Ваша корзина',
    'cart.page_description': 'Просмотрите товары в вашей корзине и перейдите к оформлению заказа.',
    'cart.empty_title': 'Ваша корзина пуста',
    'cart.empty_description': 'Похоже, вы еще ничего не добавили в корзину.',
    'cart.start_shopping': 'Начать покупки',
    'cart.order_summary_title': 'Сводка заказа',
    'cart.subtotal_label': 'Подытог ({count} {noun})',
    'cart.shipping_label': 'Доставка',
    'cart.shipping_value_placeholder': 'Рассчитывается при оформлении',
    'cart.total_label': 'Итого',
    'cart.proceed_to_checkout_button': 'Перейти к оформлению',
    'cart.clear_cart_button': 'Очистить корзину',
    'cart.item_price_label': 'Цена',
    'cart.item_subtotal_label': 'Подытог',
    'cart.remove_item_aria': 'Удалить товар',
    'cart.item_quantity_aria': 'Количество товара',
    'cart.toast_item_removed_title': 'Товар удален',
    'cart.toast_item_removed_desc': '{name} удален из вашей корзины.',

    'checkout.page_title': 'Оформление заказа',
    'checkout.step_shipping': 'Доставка',
    'checkout.step_payment': 'Оплата',
    'checkout.step_review': 'Проверка',
    'checkout.step_confirmation': 'Подтверждение',
    'checkout.loading_stepper': 'Загрузка шагов...',
    'checkout.loading_data': 'Загрузка данных заказа...',
    'checkout.redirect_to_cart_empty': 'Корзина пуста. Перенаправление в корзину...',
    'checkout.redirect_to_shipping_no_address': 'Адрес доставки не указан. Перенаправление...',
    'checkout.redirect_to_payment_no_method': 'Способ оплаты не выбран. Перенаправление...',

    'checkout.shipping.title': 'Адрес доставки',
    'checkout.shipping.description': 'Введите информацию для доставки вашего заказа.',
    'checkout.shipping.full_name_label': 'Полное имя',
    'checkout.shipping.full_name_placeholder': 'Иван Иванов',
    'checkout.shipping.email_label': 'Email',
    'checkout.shipping.email_placeholder': 'you@example.com',
    'checkout.shipping.phone_label': 'Номер телефона',
    'checkout.shipping.phone_placeholder': '+7 (700) 123-45-67',
    'checkout.shipping.address1_label': 'Адрес (строка 1)',
    'checkout.shipping.address1_placeholder': 'ул. Абая, 123',
    'checkout.shipping.address2_label': 'Адрес (строка 2, необязательно)',
    'checkout.shipping.address2_placeholder': 'кв. 45, подъезд 2',
    'checkout.shipping.city_label': 'Город',
    'checkout.shipping.city_placeholder': 'Алматы',
    'checkout.shipping.postal_code_label': 'Почтовый индекс',
    'checkout.shipping.postal_code_placeholder': '050000',
    'checkout.shipping.country_label': 'Страна',
    'checkout.shipping.country_value_default': 'Казахстан',
    'checkout.shipping.button_back_to_cart': 'Вернуться в корзину',
    'checkout.shipping.button_to_payment': 'Продолжить к оплате',
    'checkout.shipping.validation_fullname_required': 'Полное имя обязательно.',
    'checkout.shipping.validation_email_invalid': 'Введите действительный email.',
    'checkout.shipping.validation_phone_required': 'Номер телефона обязателен.',
    'checkout.shipping.validation_phone_invalid': 'Неверный формат номера телефона.',
    'checkout.shipping.validation_address1_required': 'Адрес (строка 1) обязателен.',
    'checkout.shipping.validation_city_required': 'Город обязателен.',
    'checkout.shipping.validation_postal_code_required': 'Почтовый индекс обязателен.',
    'checkout.shipping.validation_country_required': 'Страна обязательна.',

    'checkout.payment.title': 'Способ оплаты',
    'checkout.payment.description': 'Выберите, как вы хотите оплатить ваш заказ.',
    'checkout.payment.select_method_label': 'Выберите способ оплаты:',
    'checkout.payment.method_cod_name': 'Картой или наличными при получении',
    'checkout.payment.method_cod_desc': 'Оплатите заказ курьеру или в пункте выдачи.',
    'checkout.payment.method_kaspi_name': 'Kaspi QR (имитация)',
    'checkout.payment.method_kaspi_desc': 'Отсканируйте QR-код через приложение Kaspi.kz (имитация).',
    'checkout.payment.method_card_online_name': 'Банковской картой онлайн (имитация)',
    'checkout.payment.method_card_online_desc': 'Безопасная оплата картой Visa/Mastercard (имитация).',
    'checkout.payment.button_back_to_shipping': 'Назад к доставке',
    'checkout.payment.button_to_review': 'Продолжить к проверке',
    'checkout.payment.validation_method_required': 'Пожалуйста, выберите способ оплаты.',

    'checkout.review.title': 'Проверка заказа',
    'checkout.review.description': 'Пожалуйста, проверьте все детали вашего заказа перед подтверждением.',
    'checkout.review.cart_items_title': 'Товары в корзине ({count} {noun})',
    'checkout.review.subtotal_label': 'Подытог:',
    'checkout.review.shipping_address_title': 'Адрес доставки',
    'checkout.review.payment_method_title': 'Способ оплаты',
    'checkout.review.shipping_cost_label': 'Доставка:',
    'checkout.review.shipping_cost_value': 'Рассчитывается (0 ₸ для имитации)',
    'checkout.review.total_payable_label': 'Итого к оплате:',
    'checkout.review.button_back_to_payment': 'Назад к оплате',
    'checkout.review.button_place_order': 'Разместить заказ',
    'checkout.review.button_placing_order': 'Размещение...',
    'checkout.review.error_missing_data': 'Отсутствуют данные заказа, невозможно разместить заказ.',

    'checkout.confirmation.page_title': 'Заказ подтвержден',
    'checkout.confirmation.loading_text': 'Загрузка подтверждения...',
    'checkout.confirmation.error_title': 'Ошибка',
    'checkout.confirmation.error_no_order_id': 'Номер заказа не найден. Перенаправление...',
    'checkout.confirmation.button_to_home': 'На главную',
    'checkout.confirmation.success_title': 'Заказ успешно размещен!',
    'checkout.confirmation.thank_you_message': 'Спасибо за вашу покупку в TechShop.',
    'checkout.confirmation.order_number_label': 'Номер вашего заказа:',
    'checkout.confirmation.email_sent_message': 'Мы отправили подтверждение заказа на ваш email (имитация). Вы можете отслеживать статус вашего заказа в личном кабинете (функция в разработке).',
    'checkout.confirmation.button_continue_shopping': 'Продолжить покупки',
    'checkout.confirmation.button_to_profile': 'Перейти в профиль',

    'login.page_title': 'Вход',
    'login.card_title': 'Вход в TechShop',
    'login.card_description': 'Введите свои данные для доступа к аккаунту.',
    'login.email_label': 'Email',
    'login.email_placeholder': 'you@example.com',
    'login.password_label': 'Пароль',
    'login.password_placeholder': '••••••••',
    'login.submit_button': 'Войти',
    'login.loading_button': 'Вход...',
    'login.no_account_text': 'Нет аккаунта?',
    'login.register_link': 'Зарегистрироваться',
    'login.toast_success_title': 'Успешный вход!',
    'login.toast_success_desc': 'Вы успешно вошли в систему.',
    'login.toast_error_title': 'Ошибка входа',
    'login.toast_error_generic_desc': 'Произошла ошибка при входе. Попробуйте еще раз.',
    'login.toast_error_invalid_credentials_desc': 'Неверный email или пароль. Пожалуйста, проверьте введенные данные.',
    'login.toast_error_invalid_email_desc': 'Некорректный формат email.',
    'login.toast_error_too_many_requests_desc': 'Слишком много попыток входа. Пожалуйста, попробуйте позже.',
    'login.toast_error_firebase_api_key_invalid': 'Ошибка конфигурации Firebase: недействительный API ключ. Пожалуйста, проверьте файл src/lib/firebase.ts и ваши переменные окружения (.env.local).',
    'login.validation_email_invalid': 'Пожалуйста, введите действительный email.',
    'login.validation_password_empty': 'Пароль не может быть пустым.',

    'register.page_title': 'Регистрация',
    'register.card_title': 'Регистрация в TechShop',
    'register.card_description': 'Создайте новый аккаунт, чтобы начать покупки.',
    'register.email_label': 'Email',
    'register.email_placeholder': 'you@example.com',
    'register.password_label': 'Пароль',
    'register.password_placeholder': '••••••••',
    'register.confirm_password_label': 'Подтвердите пароль',
    'register.confirm_password_placeholder': '••••••••',
    'register.submit_button': 'Зарегистрироваться',
    'register.loading_button': 'Регистрация...',
    'register.has_account_text': 'Уже есть аккаунт?',
    'register.login_link': 'Войти',
    'register.toast_success_title': 'Успешная регистрация!',
    'register.toast_success_desc': 'Вы успешно зарегистрированы. Теперь вы можете войти.',
    'register.toast_error_title': 'Ошибка регистрации',
    'register.toast_error_generic_desc': 'Произошла ошибка при регистрации. Попробуйте еще раз.',
    'register.toast_error_email_in_use_desc': 'Этот email уже используется. Пожалуйста, используйте другой email или войдите.',
    'register.toast_error_weak_password_desc': 'Пароль слишком слабый. Пожалуйста, используйте более надежный пароль (минимум 6 символов).',
    'register.toast_error_invalid_email_desc': 'Некорректный формат email.',
    'register.toast_error_firebase_api_key_invalid': 'Ошибка конфигурации Firebase: недействительный API ключ. Пожалуйста, проверьте файл src/lib/firebase.ts и ваши переменные окружения (.env.local), чтобы убедиться, что указан правильный API ключ вашего Firebase проекта.',
    'register.toast_error_operation_not_allowed': 'Ошибка регистрации: вход по email/паролю не включен в вашем Firebase проекте. Пожалуйста, включите его в консоли Firebase -> Authentication -> Sign-in method.',
    'register.validation_email_invalid': 'Пожалуйста, введите действительный email.',
    'register.validation_password_min_length': 'Пароль должен содержать не менее 6 символов.',
    'register.validation_passwords_do_not_match': 'Пароли не совпадают.',

    'wishlist.page_title': 'Избранное',
    'wishlist.title': 'Избранные товары',
    'wishlist.count_text': 'В избранном: {count} {noun}',
    'wishlist.empty_title': 'Ваше избранное пусто',
    'wishlist.empty_description': 'Добавляйте товары в избранное, нажимая на сердечко рядом с ними.',
    'wishlist.button_go_shopping': 'Перейти к покупкам',

    'homepage.hero_title': 'Добро пожаловать в TechShop',
    'homepage.hero_subtitle': 'Ваш главный поставщик новейшей и лучшей электроники. Откройте мир инноваций!',
    'homepage.hero_button': 'В магазин электроники',
    'homepage.about_title': 'О TechShop',
    'homepage.about_text': 'TechShop - ваш надежный партнер в мире современной электроники. Мы стремимся предоставлять вам доступ к самым последним технологическим новинкам, сочетая высокое качество с отличным сервисом и выгодными условиями.',
    'homepage.usp_delivery_title': 'Быстрая доставка',
    'homepage.usp_delivery_text': 'Оперативная доставка по всему Казахстану.',
    'homepage.usp_quality_title': 'Гарантия качества',
    'homepage.usp_quality_text': 'Официальная гарантия на все товары от производителя.',
    'homepage.usp_exclusive_title': 'Эксклюзивные товары',
    'homepage.usp_exclusive_text': 'Регулярные акции и специальные предложения.',
    'homepage.featured_title': 'Рекомендуемая электроника',
    'homepage.new_arrivals_title': 'Новые поступления',
    'homepage.view_all_new_arrivals_button': 'Смотреть все новинки',
    'homepage.special_offers_title': 'Специальные предложения',
    'homepage.promo_smartphones_title': 'Скидки на Смартфоны!',
    'homepage.promo_smartphones_text': 'До -20% на популярные модели. Обновите свой гаджет уже сегодня!',
    'homepage.promo_smartphones_button': 'Смотреть смартфоны',
    'homepage.promo_hot_deal_title': 'Горячее предложение!',
    'homepage.promo_hot_deal_price_prefix': 'Супер цена:',
    'homepage.promo_hot_deal_button': 'Узнать больше',

    'profile.welcome': 'Добро пожаловать',
    'profile.manage_info': 'Управляйте вашей информацией, заказами и настройками.',
    'profile.personal_info': 'Личная информация',
    'profile.personal_info_desc': 'Ваши основные данные учетной записи.',
    'profile.email': 'Email',
    'profile.name': 'Имя',
    'profile.edit_profile_wip': 'Редактировать профиль (в разработке)',
    'profile.order_history': 'История заказов',
    'profile.order_history_count': '({count} {noun})',
    'profile.order_history_desc': 'Просмотр ваших прошлых и текущих заказов.',
    'profile.no_orders': 'У вас пока нет размещенных заказов.',
    'profile.order_label_prefix': 'Заказ #',
    'profile.order_date_label': 'Дата:',
    'profile.order_status_label': 'Статус:',
    'profile.order_status_pending': 'В ожидании',
    'profile.order_status_processing': 'В обработке',
    'profile.order_status_shipped': 'Отправлен',
    'profile.order_status_delivered': 'Доставлен',
    'profile.order_status_cancelled': 'Отменен',
    'profile.order_status_unknown': 'Неизвестен',
    'profile.order_total_amount': 'Сумма',
    'profile.order_items_label': 'Товары:',
    'profile.order_shipping_label': 'Доставка:',
    'profile.order_payment_label': 'Оплата:',
    'profile.account_settings': 'Настройки аккаунта',
    'profile.account_settings_desc': 'Управление параметрами вашей учетной записи.',
    'profile.change_password_wip': 'Изменить пароль (в разработке)',
    'profile.manage_addresses_wip': 'Управление адресами (в разработке)',
    'profile.language_settings': 'Настройки языка',
    'profile.language_settings_desc': 'Выберите предпочитаемый язык интерфейса.',
    'profile.app_language': 'Язык приложения',
    'profile.select_language': 'Выберите язык',
    'profile.language_russian': 'Русский',
    'profile.language_english': 'English',
    'profile.language_kazakh': 'Қазақша',
    'profile.language_change_note': 'Полная смена языка интерфейса будет доступна в следующих обновлениях.',
    'profile.logout': 'Выйти из аккаунта',
    'profile.logout_success_desc': 'Вы успешно вышли из системы.',
    'profile.redirecting_to_login': 'Перенаправление на страницу входа...',
    'profile.user_avatar_fallback_prefix': 'П',
    'toast.lang_changed_title': 'Настройки языка',
    'toast.lang_changed_desc_ru': 'Язык изменен на Русский.',
    'toast.lang_changed_desc_en': 'Language changed to English.',
    'toast.lang_changed_desc_kk': 'Тіл Қазақшаға өзгертілді.',
    'toast.logout_success_title': 'Выход из системы',
    'toast.logout_error_title': 'Ошибка выхода',
    'toast.logout_error_desc': 'Не удалось выйти из системы. Попробуйте еще раз.',

    'noun.product': { one: 'товар', few: 'товара', many: 'товаров' },
    'noun.review': { one: 'отзыв', few: 'отзыва', many: 'отзывов' },
    'noun.item': { one: 'товар', few: 'товара', many: 'товаров' },
    'noun.order': { one: 'заказ', few: 'заказа', many: 'заказов' },

    'category.phones-gadgets': 'Телефоны и гаджеты',
    'category.smartphones': 'Смартфоны',
    'category.smartphone-accessories': 'Аксессуары для смартфонов',
    'category.feature-phones': 'Кнопочные телефоны',
    'category.smartwatches-bands': 'Умные часы и браслеты',
    'category.laptops-computers': 'Ноутбуки и компьютеры',
    'category.laptops': 'Ноутбуки',
    'category.tablets': 'Планшеты',
    'category.desktops-all-in-ones': 'Настольные ПК и Моноблоки',
    'category.monitors': 'Мониторы',
    'category.pc-components': 'Комплектующие для ПК',
    'category.peripherals-accessories': 'Периферия и аксессуары',
    'category.audio-devices': 'Аудиотехника',
    'category.headphones-headsets': 'Наушники и гарнитуры',
    'category.portable-speakers': 'Портативные колонки',
    'category.home-audio-systems': 'Домашние аудиосистемы',
    'category.photo-video': 'Фото и видео',
    'category.cameras': 'Фотоаппараты',
    'category.camcorders': 'Видеокамеры',
    'category.action-cameras': 'Экшн-камеры',
    'category.drones-quadcopters': 'Дроны и квадрокоптеры',
    'category.photo-video-accessories': 'Аксессуары для фото и видео',
    'category.smart-home': 'Умный дом',
    'category.smart-security': 'Системы безопасности',
    'category.smart-lighting': 'Умное освещение',
    'category.smart-plugs-switches': 'Умные розетки и выключатели',
    'category.smart-climate': 'Климат-контроль',

    'color.midnight black': 'Черный как ночь',
    'color.nebula blue': 'Туманно-синий',
    'color.space gray': 'Серый космос',
    'color.graphite black': 'Графитово-черный',
    'color.obsidian black': 'Обсидианово-черный',
    'color.natural titanium': 'Натуральный титан',
    'color.titanium gray': 'Титановый серый',
    'color.black': 'Черный',
    'color.asteroid black': 'Астероидно-черный',
    'color.starry night': 'Звездная ночь',
    'color.silver': 'Серебристый',
    'color.space black': 'Черный космос',
    'color.blue': 'Синий',
    'color.eclipse gray': 'Сумрачно-серый',
    'color.inkwell gray': 'Чернильно-серый',
    'color.cool silver': 'Холодный серебристый',
    'color.grey': 'Серый',
    'color.charcoal': 'Угольный',
  },
  en: {
    'app.name': 'TechShop',
    'nav.catalog': 'Catalog',
    'nav.menu_open_aria': 'Open menu',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'footer.copyright': '© {year} TechShop. All rights reserved.',
    'footer.powered_by': 'Powered by Next.js and ShadCN UI',

    'search.placeholder': 'Search products...',
    'search.submit_aria_label': 'Submit search',
    'search.loading': 'Loading...',
    'search.no_results_for_query': 'No products found for "{query}".',
    'search.show_all_results_for_query': 'Show all results for "{query}"',
    'search.title': 'Search Products',
    'search.enter_query_placeholder': 'Enter your search query in the search bar above to find products.',
    'search.results_title': 'Search results for: "{query}"',
    'search.found_count': 'Found: {count} {noun}',

    'product.brand': 'Brand',
    'product.rating': 'Rating',
    'product.reviews_count_parentheses': '({count} {noun})',
    'product.characteristics': 'Features',
    'product.sku': 'SKU',
    'product.availability': 'Availability',
    'product.availability_available': '{stock} {noun} available',
    'product.availability_out_of_stock': 'Out of stock',
    'product.add_to_cart': 'Add to Cart',
    'product.go_to_product': 'View Product',
    'product.delivery_estimate': 'Estimated delivery: 2-5 days.',
    'product.payment_methods_note': 'Available payment methods: Kaspi, Visa, MasterCard.',
    'product.add_to_wishlist_aria': 'Add to wishlist',
    'product.remove_from_wishlist_aria': 'Remove from wishlist',
    'product.toast_added_to_cart_title': 'Added to Cart',
    'product.toast_added_to_cart_desc': '{name} has been added to your cart ({count} item(s)).',
    'product.toast_added_to_wishlist_title': 'Added to Wishlist',
    'product.toast_added_to_wishlist_desc': '{name} has been added to your wishlist.',
    'product.toast_removed_from_wishlist_title': 'Removed from Wishlist',
    'product.toast_removed_from_wishlist_desc': '{name} has been removed from your wishlist.',
    'product.quantity_aria': 'Quantity',
    'product.decrease_quantity_aria': 'Decrease quantity',
    'product.increase_quantity_aria': 'Increase quantity',
    'product.page_title': 'Products',
    'product.page_description': 'Browse all our products at TechShop. Filter by price, brand, and other features.',
    'product.all_products_title': 'All Products',
    'product.category_not_found_title': 'Category Not Found',
    'product.search_results_in_category_title': 'Search results for "{query}" in "{categoryName}"',
    'product.no_products_found_generic': 'No products found.',
    'product.no_products_in_category': 'No products found in category "{categoryName}".',
    'product.product_not_found_title': 'Product Not Found',

    'filter.sidebar_title': 'Filters',
    'filter.reset_all': 'Reset All',
    'filter.price_label': 'Price',
    'filter.brand_label': 'Brand',
    'filter.color_label': 'Color',
    'filter.min_price_aria': 'Minimum price',
    'filter.max_price_aria': 'Maximum price',
    'filter.applied_filters': 'Applied Filters:',
    'filter.remove_filter_aria': 'Remove filter {label}',
    'filter.price_range_label': 'Price: {minPrice} - {maxPrice} ₸',
    'filter.brand_filter_label': 'Brand: {brand}',
    'filter.color_filter_label': 'Color: {color}',
    'filter.mobile_filters_button': 'Filters',
    'filter.category_filter_title': 'Filter by Category',
    'filter.select_category_placeholder': 'Select category',
    'filter.all_categories': 'All Categories',

    'sort.label': 'Sort by:',
    'sort.placeholder': 'Select sorting',
    'sort.popularity': 'Popularity',
    'sort.price_asc': 'Price: Low to High',
    'sort.price_desc': 'Price: High to Low',
    'sort.newest': 'Newest',
    'sort.name_asc': 'Name: A-Z',
    'sort.name_desc': 'Name: Z-A',

    'reviews.title': 'Customer Reviews ({count} {noun})',
    'reviews.average_rating': 'Average rating: {rating} out of 5',
    'reviews.no_reviews': 'There are no reviews for this product yet.',
    'reviews.leave_review_title': 'Leave a Review',
    'reviews.leave_review_description': 'Share your opinion about the product with other customers.',
    'reviews.your_rating_label': 'Your Rating',
    'reviews.your_comment_label': 'Your Review',
    'reviews.comment_placeholder': 'Write what you think about the product...',
    'reviews.submit_button': 'Submit Review',
    'reviews.submitting_button': 'Submitting...',
    'reviews.toast_submitted_title': 'Review Added!',
    'reviews.toast_submitted_desc': 'Thank you for your review.',
    'reviews.toast_error_title': 'Error',
    'reviews.toast_error_desc': 'Failed to add review. Please try again.',
    'reviews.toast_auth_error_desc': 'You must be logged in to leave a review.',
    'reviews.login_prompt_title': 'Want to leave a review?',
    'reviews.login_prompt_text_before_links': '',
    'reviews.login_prompt_login_link': 'Log in',
    'reviews.login_prompt_text_between_links': ' or ',
    'reviews.login_prompt_register_link': 'register',
    'reviews.login_prompt_text_after_links': ' to share your opinion about the product.',
    'reviews.purchase_required_title': 'Share Your Opinion',
    'reviews.purchase_required_text': 'You can review this product after purchasing it.',
    'reviews.already_reviewed_title': 'Thank You for Your Review!',
    'reviews.already_reviewed_text': 'You have already reviewed this product.',
    'reviews.loading_auth_status': 'Checking authorization status...',
    'reviews.rating_required': 'Please provide a rating.',
    'reviews.comment_min_length': 'Review must be at least 10 characters long.',
    'reviews.comment_max_length': 'Review must not exceed 1000 characters.',
    'user.anonymous': 'Anonymous User',


    'cart.page_title': 'Your Cart',
    'cart.page_description': 'Review items in your cart and proceed to checkout.',
    'cart.empty_title': 'Your cart is empty',
    'cart.empty_description': 'Looks like you haven\'t added anything to your cart yet.',
    'cart.start_shopping': 'Start Shopping',
    'cart.order_summary_title': 'Order Summary',
    'cart.subtotal_label': 'Subtotal ({count} {noun})',
    'cart.shipping_label': 'Shipping',
    'cart.shipping_value_placeholder': 'Calculated at checkout',
    'cart.total_label': 'Total',
    'cart.proceed_to_checkout_button': 'Proceed to Checkout',
    'cart.clear_cart_button': 'Clear Cart',
    'cart.item_price_label': 'Price',
    'cart.item_subtotal_label': 'Subtotal',
    'cart.remove_item_aria': 'Remove item',
    'cart.item_quantity_aria': 'Item quantity',
    'cart.toast_item_removed_title': 'Item Removed',
    'cart.toast_item_removed_desc': '{name} has been removed from your cart.',

    'checkout.page_title': 'Checkout',
    'checkout.step_shipping': 'Shipping',
    'checkout.step_payment': 'Payment',
    'checkout.step_review': 'Review',
    'checkout.step_confirmation': 'Confirmation',
    'checkout.loading_stepper': 'Loading steps...',
    'checkout.loading_data': 'Loading order data...',
    'checkout.redirect_to_cart_empty': 'Cart is empty. Redirecting to cart...',
    'checkout.redirect_to_shipping_no_address': 'Shipping address not provided. Redirecting...',
    'checkout.redirect_to_payment_no_method': 'Payment method not selected. Redirecting...',

    'checkout.shipping.title': 'Shipping Address',
    'checkout.shipping.description': 'Enter your information to ship your order.',
    'checkout.shipping.full_name_label': 'Full Name',
    'checkout.shipping.full_name_placeholder': 'John Doe',
    'checkout.shipping.email_label': 'Email',
    'checkout.shipping.email_placeholder': 'you@example.com',
    'checkout.shipping.phone_label': 'Phone Number',
    'checkout.shipping.phone_placeholder': '+1 (555) 123-4567',
    'checkout.shipping.address1_label': 'Address Line 1',
    'checkout.shipping.address1_placeholder': '123 Main St',
    'checkout.shipping.address2_label': 'Address Line 2 (optional)',
    'checkout.shipping.address2_placeholder': 'Apt 4B',
    'checkout.shipping.city_label': 'City',
    'checkout.shipping.city_placeholder': 'New York',
    'checkout.shipping.postal_code_label': 'Postal Code',
    'checkout.shipping.postal_code_placeholder': '10001',
    'checkout.shipping.country_label': 'Country',
    'checkout.shipping.country_value_default': 'USA',
    'checkout.shipping.button_back_to_cart': 'Back to Cart',
    'checkout.shipping.button_to_payment': 'Continue to Payment',
    'checkout.shipping.validation_fullname_required': 'Full name is required.',
    'checkout.shipping.validation_email_invalid': 'Enter a valid email.',
    'checkout.shipping.validation_phone_required': 'Phone number is required.',
    'checkout.shipping.validation_phone_invalid': 'Invalid phone number format.',
    'checkout.shipping.validation_address1_required': 'Address line 1 is required.',
    'checkout.shipping.validation_city_required': 'City is required.',
    'checkout.shipping.validation_postal_code_required': 'Postal code is required.',
    'checkout.shipping.validation_country_required': 'Country is required.',

    'checkout.payment.title': 'Payment Method',
    'checkout.payment.description': 'Choose how you want to pay for your order.',
    'checkout.payment.select_method_label': 'Select payment method:',
    'checkout.payment.method_cod_name': 'Cash or Card on Delivery',
    'checkout.payment.method_cod_desc': 'Pay the courier or at the pickup point.',
    'checkout.payment.method_kaspi_name': 'Kaspi QR (simulation)',
    'checkout.payment.method_kaspi_desc': 'Scan QR code via Kaspi.kz app (simulation).',
    'checkout.payment.method_card_online_name': 'Credit Card Online (simulation)',
    'checkout.payment.method_card_online_desc': 'Secure payment with Visa/Mastercard (simulation).',
    'checkout.payment.button_back_to_shipping': 'Back to Shipping',
    'checkout.payment.button_to_review': 'Continue to Review',
    'checkout.payment.validation_method_required': 'Please select a payment method.',

    'checkout.review.title': 'Review Order',
    'checkout.review.description': 'Please check all your order details before confirming.',
    'checkout.review.cart_items_title': 'Items in Cart ({count} {noun})',
    'checkout.review.subtotal_label': 'Subtotal:',
    'checkout.review.shipping_address_title': 'Shipping Address',
    'checkout.review.payment_method_title': 'Payment Method',
    'checkout.review.shipping_cost_label': 'Shipping:',
    'checkout.review.shipping_cost_value': 'Calculated (0 ₸ for simulation)',
    'checkout.review.total_payable_label': 'Total Payable:',
    'checkout.review.button_back_to_payment': 'Back to Payment',
    'checkout.review.button_place_order': 'Place Order',
    'checkout.review.button_placing_order': 'Placing...',
    'checkout.review.error_missing_data': 'Missing order data, cannot place order.',

    'checkout.confirmation.page_title': 'Order Confirmed',
    'checkout.confirmation.loading_text': 'Loading confirmation...',
    'checkout.confirmation.error_title': 'Error',
    'checkout.confirmation.error_no_order_id': 'Order number not found. Redirecting...',
    'checkout.confirmation.button_to_home': 'To Homepage',
    'checkout.confirmation.success_title': 'Order Placed Successfully!',
    'checkout.confirmation.thank_you_message': 'Thank you for your purchase at TechShop.',
    'checkout.confirmation.order_number_label': 'Your order number is:',
    'checkout.confirmation.email_sent_message': 'We have sent an order confirmation to your email (simulation). You can track your order status in your account (feature in development).',
    'checkout.confirmation.button_continue_shopping': 'Continue Shopping',
    'checkout.confirmation.button_to_profile': 'Go to Profile',

    'login.page_title': 'Login',
    'login.card_title': 'Login to TechShop',
    'login.card_description': 'Enter your details to access your account.',
    'login.email_label': 'Email',
    'login.email_placeholder': 'you@example.com',
    'login.password_label': 'Password',
    'login.password_placeholder': '••••••••',
    'login.submit_button': 'Login',
    'login.loading_button': 'Logging in...',
    'login.no_account_text': 'No account?',
    'login.register_link': 'Register',
    'login.toast_success_title': 'Login Successful!',
    'login.toast_success_desc': 'You have successfully logged in.',
    'login.toast_error_title': 'Login Error',
    'login.toast_error_generic_desc': 'An error occurred during login. Please try again.',
    'login.toast_error_invalid_credentials_desc': 'Invalid email or password. Please check your credentials.',
    'login.toast_error_invalid_email_desc': 'Invalid email format.',
    'login.toast_error_too_many_requests_desc': 'Too many login attempts. Please try again later.',
    'login.toast_error_firebase_api_key_invalid': 'Firebase configuration error: Invalid API key. Please check your src/lib/firebase.ts file and your environment variables (.env.local).',
    'login.validation_email_invalid': 'Please enter a valid email.',
    'login.validation_password_empty': 'Password cannot be empty.',

    'register.page_title': 'Register',
    'register.card_title': 'Register for TechShop',
    'register.card_description': 'Create a new account to start shopping.',
    'register.email_label': 'Email',
    'register.email_placeholder': 'you@example.com',
    'register.password_label': 'Password',
    'register.password_placeholder': '••••••••',
    'register.confirm_password_label': 'Confirm Password',
    'register.confirm_password_placeholder': '••••••••',
    'register.submit_button': 'Register',
    'register.loading_button': 'Registering...',
    'register.has_account_text': 'Already have an account?',
    'register.login_link': 'Login',
    'register.toast_success_title': 'Registration Successful!',
    'register.toast_success_desc': 'You have successfully registered. You can now log in.',
    'register.toast_error_title': 'Registration Error',
    'register.toast_error_generic_desc': 'An error occurred during registration. Please try again.',
    'register.toast_error_email_in_use_desc': 'This email is already in use. Please use a different email or log in.',
    'register.toast_error_weak_password_desc': 'Password is too weak. Please use a stronger password (at least 6 characters).',
    'register.toast_error_invalid_email_desc': 'Invalid email format.',
    'register.toast_error_firebase_api_key_invalid': 'Firebase configuration error: Invalid API key. Please check your src/lib/firebase.ts file and your environment variables (.env.local) to ensure the correct API key for your Firebase project is provided.',
    'register.toast_error_operation_not_allowed': 'Registration error: Email/password sign-in is not enabled in your Firebase project. Please enable it in Firebase console -> Authentication -> Sign-in method.',
    'register.validation_email_invalid': 'Please enter a valid email.',
    'register.validation_password_min_length': 'Password must be at least 6 characters.',
    'register.validation_passwords_do_not_match': 'Passwords do not match.',

    'wishlist.page_title': 'Wishlist',
    'wishlist.title': 'Favorite Products',
    'wishlist.count_text': 'In wishlist: {count} {noun}',
    'wishlist.empty_title': 'Your wishlist is empty',
    'wishlist.empty_description': 'Add products to your wishlist by clicking the heart icon next to them.',
    'wishlist.button_go_shopping': 'Go Shopping',

    'homepage.hero_title': 'Welcome to TechShop',
    'homepage.hero_subtitle': 'Your premier destination for the latest and greatest in electronics. Discover a world of innovation!',
    'homepage.hero_button': 'Shop Electronics',
    'homepage.about_title': 'About TechShop',
    'homepage.about_text': 'TechShop is your trusted partner in the world of modern electronics. We strive to provide you with access to the latest technological innovations, combining high quality with excellent service and favorable conditions.',
    'homepage.usp_delivery_title': 'Fast Delivery',
    'homepage.usp_delivery_text': 'Prompt delivery throughout Kazakhstan.',
    'homepage.usp_quality_title': 'Quality Guarantee',
    'homepage.usp_quality_text': 'Official manufacturer warranty on all goods.',
    'homepage.usp_exclusive_title': 'Exclusive Products',
    'homepage.usp_exclusive_text': 'Regular promotions and special offers.',
    'homepage.featured_title': 'Featured Electronics',
    'homepage.new_arrivals_title': 'New Arrivals',
    'homepage.view_all_new_arrivals_button': 'View All New Arrivals',
    'homepage.special_offers_title': 'Special Offers',
    'homepage.promo_smartphones_title': 'Smartphone Sale!',
    'homepage.promo_smartphones_text': 'Up to -20% on popular models. Upgrade your gadget today!',
    'homepage.promo_smartphones_button': 'Shop Smartphones',
    'homepage.promo_hot_deal_title': 'Hot Deal!',
    'homepage.promo_hot_deal_price_prefix': 'Super Price:',
    'homepage.promo_hot_deal_button': 'Learn More',

    'profile.welcome': 'Welcome',
    'profile.manage_info': 'Manage your information, orders, and settings.',
    'profile.personal_info': 'Personal Information',
    'profile.personal_info_desc': 'Your main account details.',
    'profile.email': 'Email',
    'profile.name': 'Name',
    'profile.edit_profile_wip': 'Edit Profile (work in progress)',
    'profile.order_history': 'Order History',
    'profile.order_history_count': '({count} {noun})',
    'profile.order_history_desc': 'View your past and current orders.',
    'profile.no_orders': 'You have no placed orders yet.',
    'profile.order_label_prefix': 'Order #',
    'profile.order_date_label': 'Date:',
    'profile.order_status_label': 'Status:',
    'profile.order_status_pending': 'Pending',
    'profile.order_status_processing': 'Processing',
    'profile.order_status_shipped': 'Shipped',
    'profile.order_status_delivered': 'Delivered',
    'profile.order_status_cancelled': 'Cancelled',
    'profile.order_status_unknown': 'Unknown',
    'profile.order_total_amount': 'Total',
    'profile.order_items_label': 'Items:',
    'profile.order_shipping_label': 'Shipping:',
    'profile.order_payment_label': 'Payment:',
    'profile.account_settings': 'Account Settings',
    'profile.account_settings_desc': 'Manage your account parameters.',
    'profile.change_password_wip': 'Change Password (work in progress)',
    'profile.manage_addresses_wip': 'Manage Addresses (work in progress)',
    'profile.language_settings': 'Language Settings',
    'profile.language_settings_desc': 'Choose your preferred interface language.',
    'profile.app_language': 'Application Language',
    'profile.select_language': 'Select language',
    'profile.language_russian': 'Русский',
    'profile.language_english': 'English',
    'profile.language_kazakh': 'Қазақша',
    'profile.language_change_note': 'Full interface language change will be available in future updates.',
    'profile.logout': 'Logout',
    'profile.logout_success_desc': 'You have been successfully logged out.',
    'profile.redirecting_to_login': 'Redirecting to login page...',
    'profile.user_avatar_fallback_prefix': 'U',
    'toast.lang_changed_title': 'Language Settings',
    'toast.lang_changed_desc_ru': 'Язык изменен на Русский.',
    'toast.lang_changed_desc_en': 'Language changed to English.',
    'toast.lang_changed_desc_kk': 'Тіл Қазақшаға өзгертілді.',
    'toast.logout_success_title': 'Logout',
    'toast.logout_error_title': 'Logout Error',
    'toast.logout_error_desc': 'Failed to log out. Please try again.',

    'noun.product': { one: 'product', few: 'products', many: 'products' },
    'noun.review': { one: 'review', few: 'reviews', many: 'reviews' },
    'noun.item': { one: 'item', few: 'items', many: 'items' },
    'noun.order': { one: 'order', few: 'orders', many: 'orders' },

    'category.phones-gadgets': 'Phones & Gadgets',
    'category.smartphones': 'Smartphones',
    'category.smartphone-accessories': 'Smartphone Accessories',
    'category.feature-phones': 'Feature Phones',
    'category.smartwatches-bands': 'Smartwatches & Bands',
    'category.laptops-computers': 'Laptops & Computers',
    'category.laptops': 'Laptops',
    'category.tablets': 'Tablets',
    'category.desktops-all-in-ones': 'Desktops & All-in-Ones',
    'category.monitors': 'Monitors',
    'category.pc-components': 'PC Components',
    'category.peripherals-accessories': 'Peripherals & Accessories',
    'category.audio-devices': 'Audio Devices',
    'category.headphones-headsets': 'Headphones & Headsets',
    'category.portable-speakers': 'Portable Speakers',
    'category.home-audio-systems': 'Home Audio Systems',
    'category.photo-video': 'Photo & Video',
    'category.cameras': 'Cameras',
    'category.camcorders': 'Camcorders',
    'category.action-cameras': 'Action Cameras',
    'category.drones-quadcopters': 'Drones & Quadcopters',
    'category.photo-video-accessories': 'Photo & Video Accessories',
    'category.smart-home': 'Smart Home',
    'category.smart-security': 'Smart Security',
    'category.smart-lighting': 'Smart Lighting',
    'category.smart-plugs-switches': 'Smart Plugs & Switches',
    'category.smart-climate': 'Smart Climate Control',

    'color.midnight black': 'Midnight Black',
    'color.nebula blue': 'Nebula Blue',
    'color.space gray': 'Space Gray',
    'color.graphite black': 'Graphite Black',
    'color.obsidian black': 'Obsidian Black',
    'color.natural titanium': 'Natural Titanium',
    'color.titanium gray': 'Titanium Gray',
    'color.black': 'Black',
    'color.asteroid black': 'Asteroid Black',
    'color.starry night': 'Starry Night',
    'color.silver': 'Silver',
    'color.space black': 'Space Black',
    'color.blue': 'Blue',
    'color.eclipse gray': 'Eclipse Gray',
    'color.inkwell gray': 'Inkwell Gray',
    'color.cool silver': 'Cool Silver',
    'color.grey': 'Grey',
    'color.charcoal': 'Charcoal',
  },
  kk: {
    'app.name': 'TechShop',
    'nav.catalog': 'Каталог',
    'nav.menu_open_aria': 'Мәзірді ашу',
    'nav.cart': 'Себет',
    'nav.wishlist': 'Таңдаулылар',
    'nav.profile': 'Профиль',
    'nav.login': 'Кіру',
    'footer.copyright': '© {year} TechShop. Барлық құқықтар қорғалған.',
    'footer.powered_by': 'Next.js және ShadCN UI негізінде жұмыс істейді',

    'search.placeholder': 'Тауарларды іздеу...',
    'search.submit_aria_label': 'Іздеу',
    'search.loading': 'Жүктелуде...',
    'search.no_results_for_query': '"{query}" сұрауы бойынша тауарлар табылмады.',
    'search.show_all_results_for_query': '"{query}" үшін барлық нәтижелерді көрсету',
    'search.title': 'Тауарларды іздеу',
    'search.enter_query_placeholder': 'Тауарларды табу үшін жоғарыдағы іздеу жолағына сұрауыңызды енгізіңіз.',
    'search.results_title': 'Іздеу нәтижелері: "{query}"',
    'search.found_count': 'Табылды: {count} {noun}',

    'product.brand': 'Бренд',
    'product.rating': 'Рейтинг',
    'product.reviews_count_parentheses': '({count} {noun})',
    'product.characteristics': 'Сипаттамалары',
    'product.sku': 'Артикул',
    'product.availability': 'Қолжетімділігі',
    'product.availability_available': '{stock} {noun} қолжетімді',
    'product.availability_out_of_stock': 'Қоймада жоқ',
    'product.add_to_cart': 'Себетке салу',
    'product.go_to_product': 'Тауарға өту',
    'product.delivery_estimate': 'Болжалды жеткізу мерзімі: 2-5 күн.',
    'product.payment_methods_note': 'Қолжетімді төлем әдістері: Kaspi, Visa, MasterCard.',
    'product.add_to_wishlist_aria': 'Таңдаулыларға қосу',
    'product.remove_from_wishlist_aria': 'Таңдаулылардан өшіру',
    'product.toast_added_to_cart_title': 'Себетке қосылды',
    'product.toast_added_to_cart_desc': '{name} сіздің себетіңізге ({count} дана) қосылды.',
    'product.toast_added_to_wishlist_title': 'Таңдаулыларға қосылды',
    'product.toast_added_to_wishlist_desc': '{name} сіздің таңдаулыларыңызға қосылды.',
    'product.toast_removed_from_wishlist_title': 'Таңдаулылардан өшірілді',
    'product.toast_removed_from_wishlist_desc': '{name} сіздің таңдаулыларыңыздан өшірілді.',
    'product.quantity_aria': 'Саны',
    'product.decrease_quantity_aria': 'Санын азайту',
    'product.increase_quantity_aria': 'Санын көбейту',
    'product.page_title': 'Тауарлар',
    'product.page_description': 'TechShop-тағы барлық тауарларымызбен танысыңыз. Баға, бренд және басқа сипаттамалар бойынша сүзгілеңіз.',
    'product.all_products_title': 'Барлық тауарлар',
    'product.category_not_found_title': 'Санат табылмады',
    'product.search_results_in_category_title': '"{query}" сұрауы бойынша "{categoryName}" санатындағы іздеу нәтижелері',
    'product.no_products_found_generic': 'Тауарлар табылмады.',
    'product.no_products_in_category': '"{categoryName}" санатында тауарлар табылмады.',
    'product.product_not_found_title': 'Тауар табылмады',


    'filter.sidebar_title': 'Сүзгілер',
    'filter.reset_all': 'Барлығын тастау',
    'filter.price_label': 'Бағасы',
    'filter.brand_label': 'Бренд',
    'filter.color_label': 'Түсі',
    'filter.min_price_aria': 'Ең төменгі баға',
    'filter.max_price_aria': 'Ең жоғарғы баға',
    'filter.applied_filters': 'Қолданылған сүзгілер:',
    'filter.remove_filter_aria': '{label} сүзгісін жою',
    'filter.price_range_label': 'Бағасы: {minPrice} - {maxPrice} ₸',
    'filter.brand_filter_label': 'Бренд: {brand}',
    'filter.color_filter_label': 'Түсі: {color}',
    'filter.mobile_filters_button': 'Сүзгілер',
    'filter.category_filter_title': 'Санат бойынша сүзгілеу',
    'filter.select_category_placeholder': 'Санатты таңдаңыз',
    'filter.all_categories': 'Барлық санаттар',

    'sort.label': 'Сұрыптау:',
    'sort.placeholder': 'Сұрыптауды таңдаңыз',
    'sort.popularity': 'Танымалдығы бойынша',
    'sort.price_asc': 'Бағасы: өсуі бойынша',
    'sort.price_desc': 'Бағасы: кемуі бойынша',
    'sort.newest': 'Жаңалары бойынша',
    'sort.name_asc': 'Атауы: А-Я',
    'sort.name_desc': 'Атауы: Я-А',

    'reviews.title': 'Сатып алушылардың пікірлері ({count} {noun})',
    'reviews.average_rating': 'Орташа баға: {rating} / 5',
    'reviews.no_reviews': 'Бұл тауарға әлі пікірлер жоқ.',
    'reviews.leave_review_title': 'Пікір қалдыру',
    'reviews.leave_review_description': 'Тауар туралы өз пікіріңізбен басқа сатып алушылармен бөлісіңіз.',
    'reviews.your_rating_label': 'Сіздің бағаңыз',
    'reviews.your_comment_label': 'Сіздің пікіріңіз',
    'reviews.comment_placeholder': 'Тауар туралы не ойлайтыныңызды жазыңыз...',
    'reviews.submit_button': 'Пікір қалдыру',
    'reviews.submitting_button': 'Жіберу...',
    'reviews.toast_submitted_title': 'Пікір қосылды!',
    'reviews.toast_submitted_desc': 'Пікіріңіз үшін рахмет.',
    'reviews.toast_error_title': 'Қате',
    'reviews.toast_error_desc': 'Пікірді қосу мүмкін болмады. Қайталап көріңіз.',
    'reviews.toast_auth_error_desc': 'Пікір қалдыру үшін жүйеге кіруіңіз керек.',
    'reviews.login_prompt_title': 'Пікір қалдырғыңыз келе ме?',
    'reviews.login_prompt_text_before_links': '',
    'reviews.login_prompt_login_link': 'Кіріңіз',
    'reviews.login_prompt_text_between_links': ' немесе ',
    'reviews.login_prompt_register_link': 'тіркеліңіз',
    'reviews.login_prompt_text_after_links': ', тауар туралы өз пікіріңізбен бөлісу үшін.',
    'reviews.purchase_required_title': 'Пікіріңізбен бөлісіңіз',
    'reviews.purchase_required_text': 'Бұл тауарды сатып алғаннан кейін пікір қалдыра аласыз.',
    'reviews.already_reviewed_title': 'Пікіріңіз үшін рахмет!',
    'reviews.already_reviewed_text': 'Сіз бұл тауарға пікір қалдырдыңыз.',
    'reviews.loading_auth_status': 'Авторизация күйін тексеру...',
    'reviews.rating_required': 'Баға қойыңыз.',
    'reviews.comment_min_length': 'Пікір кемінде 10 таңбадан тұруы керек.',
    'reviews.comment_max_length': 'Пікір 1000 таңбадан аспауы керек.',
    'user.anonymous': 'Анонимді пайдаланушы',


    'cart.page_title': 'Сіздің себетіңіз',
    'cart.page_description': 'Себеттегі тауарларды қарап шығып, тапсырыс беруге өтіңіз.',
    'cart.empty_title': 'Сіздің себетіңіз бос',
    'cart.empty_description': 'Себетіңізге әлі ештеңе қоспағансыз.',
    'cart.start_shopping': 'Сатып алуды бастау',
    'cart.order_summary_title': 'Тапсырыс жиынтығы',
    'cart.subtotal_label': 'Аралық жиынтық ({count} {noun})',
    'cart.shipping_label': 'Жеткізу',
    'cart.shipping_value_placeholder': 'Тапсырыс беру кезінде есептеледі',
    'cart.total_label': 'Барлығы',
    'cart.proceed_to_checkout_button': 'Тапсырыс беруге өту',
    'cart.clear_cart_button': 'Себетті тазалау',
    'cart.item_price_label': 'Бағасы',
    'cart.item_subtotal_label': 'Аралық жиынтық',
    'cart.remove_item_aria': 'Тауарды өшіру',
    'cart.item_quantity_aria': 'Тауар саны',
    'cart.toast_item_removed_title': 'Тауар өшірілді',
    'cart.toast_item_removed_desc': '{name} сіздің себетіңізден өшірілді.',

    'checkout.page_title': 'Тапсырысты рәсімдеу',
    'checkout.step_shipping': 'Жеткізу',
    'checkout.step_payment': 'Төлем',
    'checkout.step_review': 'Тексеру',
    'checkout.step_confirmation': 'Растау',
    'checkout.loading_stepper': 'Қадамдар жүктелуде...',
    'checkout.loading_data': 'Тапсырыс деректері жүктелуде...',
    'checkout.redirect_to_cart_empty': 'Себет бос. Себетке бағытталуда...',
    'checkout.redirect_to_shipping_no_address': 'Жеткізу мекенжайы көрсетілмеген. Бағытталуда...',
    'checkout.redirect_to_payment_no_method': 'Төлем әдісі таңдалмаған. Бағытталуда...',

    'checkout.shipping.title': 'Жеткізу мекенжайы',
    'checkout.shipping.description': 'Тапсырысыңызды жеткізу үшін ақпаратты енгізіңіз.',
    'checkout.shipping.full_name_label': 'Толық аты-жөні',
    'checkout.shipping.full_name_placeholder': 'Ахметов Әли',
    'checkout.shipping.email_label': 'Email',
    'checkout.shipping.email_placeholder': 'siz@mysal.kz',
    'checkout.shipping.phone_label': 'Телефон нөмірі',
    'checkout.shipping.phone_placeholder': '+7 (700) 123-45-67',
    'checkout.shipping.address1_label': 'Мекенжай (1-жол)',
    'checkout.shipping.address1_placeholder': 'Абай к., 123',
    'checkout.shipping.address2_label': 'Мекенжай (2-жол, міндетті емес)',
    'checkout.shipping.address2_placeholder': 'пәтер 45, кіреберіс 2',
    'checkout.shipping.city_label': 'Қала',
    'checkout.shipping.city_placeholder': 'Алматы',
    'checkout.shipping.postal_code_label': 'Пошта индексі',
    'checkout.shipping.postal_code_placeholder': '050000',
    'checkout.shipping.country_label': 'Ел',
    'checkout.shipping.country_value_default': 'Қазақстан',
    'checkout.shipping.button_back_to_cart': 'Себетке оралу',
    'checkout.shipping.button_to_payment': 'Төлемге өту',
    'checkout.shipping.validation_fullname_required': 'Толық аты-жөні міндетті.',
    'checkout.shipping.validation_email_invalid': 'Жарамды email енгізіңіз.',
    'checkout.shipping.validation_phone_required': 'Телефон нөмірі міндетті.',
    'checkout.shipping.validation_phone_invalid': 'Телефон нөмірінің пішімі қате.',
    'checkout.shipping.validation_address1_required': 'Мекенжай (1-жол) міндетті.',
    'checkout.shipping.validation_city_required': 'Қала міндетті.',
    'checkout.shipping.validation_postal_code_required': 'Пошта индексі міндетті.',
    'checkout.shipping.validation_country_required': 'Ел міндетті.',

    'checkout.payment.title': 'Төлем әдісі',
    'checkout.payment.description': 'Тапсырысыңызды қалай төлегіңіз келетінін таңдаңыз.',
    'checkout.payment.select_method_label': 'Төлем әдісін таңдаңыз:',
    'checkout.payment.method_cod_name': 'Картамен немесе қолма-қол ақшамен алған кезде',
    'checkout.payment.method_cod_desc': 'Тапсырысты курьерге немесе алып кету пунктінде төлеңіз.',
    'checkout.payment.method_kaspi_name': 'Kaspi QR (имитация)',
    'checkout.payment.method_kaspi_desc': 'Kaspi.kz қосымшасы арқылы QR-кодты сканерлеңіз (имитация).',
    'checkout.payment.method_card_online_name': 'Банк картасымен онлайн (имитация)',
    'checkout.payment.method_card_online_desc': 'Visa/Mastercard картасымен қауіпсіз төлем (имитация).',
    'checkout.payment.button_back_to_shipping': 'Жеткізуге оралу',
    'checkout.payment.button_to_review': 'Тексеруге өту',
    'checkout.payment.validation_method_required': 'Төлем әдісін таңдаңыз.',

    'checkout.review.title': 'Тапсырысты тексеру',
    'checkout.review.description': 'Растамас бұрын тапсырысыңыздың барлық мәліметтерін тексеріңіз.',
    'checkout.review.cart_items_title': 'Себеттегі тауарлар ({count} {noun})',
    'checkout.review.subtotal_label': 'Аралық жиынтық:',
    'checkout.review.shipping_address_title': 'Жеткізу мекенжайы',
    'checkout.review.payment_method_title': 'Төлем әдісі',
    'checkout.review.shipping_cost_label': 'Жеткізу:',
    'checkout.review.shipping_cost_value': 'Есептеледі (имитация үшін 0 ₸)',
    'checkout.review.total_payable_label': 'Төлеуге жататын сома:',
    'checkout.review.button_back_to_payment': 'Төлемге оралу',
    'checkout.review.button_place_order': 'Тапсырысты рәсімдеу',
    'checkout.review.button_placing_order': 'Рәсімделуде...',
    'checkout.review.error_missing_data': 'Тапсырыс деректері жоқ, тапсырысты рәсімдеу мүмкін емес.',

    'checkout.confirmation.page_title': 'Тапсырыс расталды',
    'checkout.confirmation.loading_text': 'Растау жүктелуде...',
    'checkout.confirmation.error_title': 'Қате',
    'checkout.confirmation.error_no_order_id': 'Тапсырыс нөмірі табылмады. Бағытталуда...',
    'checkout.confirmation.button_to_home': 'Басты бетке',
    'checkout.confirmation.success_title': 'Тапсырыс сәтті рәсімделді!',
    'checkout.confirmation.thank_you_message': 'TechShop-тағы саудаңыз үшін рахмет.',
    'checkout.confirmation.order_number_label': 'Сіздің тапсырыс нөміріңіз:',
    'checkout.confirmation.email_sent_message': 'Біз тапсырыс растауын сіздің email-іңізге жібердік (имитация). Тапсырысыңыздың күйін жеке кабинетте бақылай аласыз (функция әзірленуде).',
    'checkout.confirmation.button_continue_shopping': 'Сатып алуды жалғастыру',
    'checkout.confirmation.button_to_profile': 'Профильге өту',

    'login.page_title': 'Кіру',
    'login.card_title': 'TechShop-қа кіру',
    'login.card_description': 'Аккаунтыңызға кіру үшін деректеріңізді енгізіңіз.',
    'login.email_label': 'Email',
    'login.email_placeholder': 'siz@mysal.kz',
    'login.password_label': 'Құпия сөз',
    'login.password_placeholder': '••••••••',
    'login.submit_button': 'Кіру',
    'login.loading_button': 'Кіруде...',
    'login.no_account_text': 'Аккаунтыңыз жоқ па?',
    'login.register_link': 'Тіркелу',
    'login.toast_success_title': 'Сәтті кіру!',
    'login.toast_success_desc': 'Сіз жүйеге сәтті кірдіңіз.',
    'login.toast_error_title': 'Кіру қатесі',
    'login.toast_error_generic_desc': 'Кіру кезінде қате пайда болды. Қайталап көріңіз.',
    'login.toast_error_invalid_credentials_desc': 'Email немесе құпия сөз қате. Енгізілген деректерді тексеріңіз.',
    'login.toast_error_invalid_email_desc': 'Email пішімі қате.',
    'login.toast_error_too_many_requests_desc': 'Кіру әрекеттері тым көп. Кейінірек қайталап көріңіз.',
    'login.toast_error_firebase_api_key_invalid': 'Firebase конфигурациясының қатесі: жарамсыз API кілті. src/lib/firebase.ts файлыңызды және орта айнымалыларыңызды (.env.local) тексеріңіз.',
    'login.validation_email_invalid': 'Жарамды email енгізіңіз.',
    'login.validation_password_empty': 'Құпия сөз бос болмауы керек.',

    'register.page_title': 'Тіркелу',
    'register.card_title': 'TechShop-та тіркелу',
    'register.card_description': 'Сатып алуды бастау үшін жаңа аккаунт жасаңыз.',
    'register.email_label': 'Email',
    'register.email_placeholder': 'siz@mysal.kz',
    'register.password_label': 'Құпия сөз',
    'register.password_placeholder': '••••••••',
    'register.confirm_password_label': 'Құпия сөзді растаңыз',
    'register.confirm_password_placeholder': '••••••••',
    'register.submit_button': 'Тіркелу',
    'register.loading_button': 'Тіркелуде...',
    'register.has_account_text': 'Аккаунтыңыз бар ма?',
    'register.login_link': 'Кіру',
    'register.toast_success_title': 'Сәтті тіркелу!',
    'register.toast_success_desc': 'Сіз сәтті тіркелдіңіз. Енді кіре аласыз.',
    'register.toast_error_title': 'Тіркелу қатесі',
    'register.toast_error_generic_desc': 'Тіркелу кезінде қате пайда болды. Қайталап көріңіз.',
    'register.toast_error_email_in_use_desc': 'Бұл email бұрыннан қолданыста. Басқа email пайдаланыңыз немесе кіріңіз.',
    'register.toast_error_weak_password_desc': 'Құпия сөз тым әлсіз. Күштірек құпия сөз пайдаланыңыз (кемінде 6 таңба).',
    'register.toast_error_invalid_email_desc': 'Email пішімі қате.',
    'register.toast_error_firebase_api_key_invalid': 'Firebase конфигурациясының қатесі: жарамсыз API кілті. Firebase жобаңыз үшін дұрыс API кілті берілгеніне көз жеткізу үшін src/lib/firebase.ts файлыңызды және орта айнымалыларыңызды (.env.local) тексеріңіз.',
    'register.toast_error_operation_not_allowed': 'Тіркелу қатесі: Firebase жобаңызда email/құпия сөз арқылы кіру қосылмаған. Оны Firebase консолінде -> Authentication -> Sign-in method бөлімінде қосыңыз.',
    'register.validation_email_invalid': 'Жарамды email енгізіңіз.',
    'register.validation_password_min_length': 'Құпия сөз кемінде 6 таңбадан тұруы керек.',
    'register.validation_passwords_do_not_match': 'Құпия сөздер сәйкес келмейді.',

    'wishlist.page_title': 'Таңдаулылар',
    'wishlist.title': 'Таңдаулы тауарлар',
    'wishlist.count_text': 'Таңдаулыларда: {count} {noun}',
    'wishlist.empty_title': 'Сіздің таңдаулыларыңыз бос',
    'wishlist.empty_description': 'Тауарлардың жанындағы жүрекше белгісін басу арқылы тауарларды таңдаулыларға қосыңыз.',
    'wishlist.button_go_shopping': 'Сатып алуға өту',

    'homepage.hero_title': 'TechShop-қа қош келдіңіз',
    'homepage.hero_subtitle': 'Ең жаңа және үздік электрониканың басты жеткізушісі. Инновациялар әлемін ашыңыз!',
    'homepage.hero_button': 'Электроника дүкеніне',
    'homepage.about_title': 'TechShop туралы',
    'homepage.about_text': 'TechShop - заманауи электроника әлеміндегі сенімді серіктесіңіз. Біз сізге жоғары сапаны тамаша сервиспен және тиімді шарттармен үйлестіре отырып, ең соңғы технологиялық жаңалықтарға қол жеткізуге тырысамыз.',
    'homepage.usp_delivery_title': 'Жылдам жеткізу',
    'homepage.usp_delivery_text': 'Қазақстан бойынша жедел жеткізу.',
    'homepage.usp_quality_title': 'Сапа кепілдігі',
    'homepage.usp_quality_text': 'Барлық тауарларға өндірушіден ресми кепілдік.',
    'homepage.usp_exclusive_title': 'Эксклюзивті тауарлар',
    'homepage.usp_exclusive_text': 'Тұрақты акциялар мен арнайы ұсыныстар.',
    'homepage.featured_title': 'Ұсынылатын электроника',
    'homepage.new_arrivals_title': 'Жаңа түсімдер',
    'homepage.view_all_new_arrivals_button': 'Барлық жаңа түсімдерді қарау',
    'homepage.special_offers_title': 'Арнайы ұсыныстар',
    'homepage.promo_smartphones_title': 'Смартфондарға жеңілдіктер!',
    'homepage.promo_smartphones_text': 'Танымал модельдерге -20% дейін. Гаджетіңізді бүгін жаңартыңыз!',
    'homepage.promo_smartphones_button': 'Смартфондарды қарау',
    'homepage.promo_hot_deal_title': 'Ыстық ұсыныс!',
    'homepage.promo_hot_deal_price_prefix': 'Супер баға:',
    'homepage.promo_hot_deal_button': 'Толығырақ білу',

    'profile.welcome': 'Қош келдіңіз',
    'profile.manage_info': 'Ақпаратыңызды, тапсырыстарыңызды және параметрлеріңізді басқарыңыз.',
    'profile.personal_info': 'Жеке ақпарат',
    'profile.personal_info_desc': 'Сіздің негізгі тіркелгі деректеріңіз.',
    'profile.email': 'Email',
    'profile.name': 'Аты',
    'profile.edit_profile_wip': 'Профильді өңдеу (әзірленуде)',
    'profile.order_history': 'Тапсырыстар тарихы',
    'profile.order_history_count': '({count} {noun})',
    'profile.order_history_desc': 'Өткен және ағымдағы тапсырыстарыңызды қарау.',
    'profile.no_orders': 'Сізде әлі тапсырыстар жоқ.',
    'profile.order_label_prefix': 'Тапсырыс #',
    'profile.order_date_label': 'Күні:',
    'profile.order_status_label': 'Мәртебесі:',
    'profile.order_status_pending': 'Күтуде',
    'profile.order_status_processing': 'Өңделуде',
    'profile.order_status_shipped': 'Жіберілді',
    'profile.order_status_delivered': 'Жеткізілді',
    'profile.order_status_cancelled': 'Бас тартылды',
    'profile.order_status_unknown': 'Белгісіз',
    'profile.order_total_amount': 'Сомасы',
    'profile.order_items_label': 'Тауарлар:',
    'profile.order_shipping_label': 'Жеткізу:',
    'profile.order_payment_label': 'Төлем:',
    'profile.account_settings': 'Тіркелгі параметрлері',
    'profile.account_settings_desc': 'Тіркелгі параметрлерін басқару.',
    'profile.change_password_wip': 'Құпия сөзді өзгерту (әзірленуде)',
    'profile.manage_addresses_wip': 'Мекенжайларды басқару (әзірленуде)',
    'profile.language_settings': 'Тіл параметрлері',
    'profile.language_settings_desc': 'Қалаған интерфейс тілін таңдаңыз.',
    'profile.app_language': 'Қолданба тілі',
    'profile.select_language': 'Тілді таңдаңыз',
    'profile.language_russian': 'Русский',
    'profile.language_english': 'English',
    'profile.language_kazakh': 'Қазақша',
    'profile.language_change_note': 'Интерфейс тілін толық өзгерту келесі жаңартуларда қолжетімді болады.',
    'profile.logout': 'Шығу',
    'profile.logout_success_desc': 'Сіз жүйеден сәтті шықтыңыз.',
    'profile.redirecting_to_login': 'Кіру бетіне бағытталуда...',
    'profile.user_avatar_fallback_prefix': 'П',
    'toast.lang_changed_title': 'Тіл параметрлері',
    'toast.lang_changed_desc_ru': 'Язык изменен на Русский.',
    'toast.lang_changed_desc_en': 'Language changed to English.',
    'toast.lang_changed_desc_kk': 'Тіл Қазақшаға өзгертілді.',
    'toast.logout_success_title': 'Жүйеден шығу',
    'toast.logout_error_title': 'Шығу қатесі',
    'toast.logout_error_desc': 'Жүйеден шығу мүмкін болмады. Қайталап көріңіз.',

    'noun.product': { one: 'тауар', few: 'тауар', many: 'тауарлар' },
    'noun.review': { one: 'пікір', few: 'пікір', many: 'пікірлер' },
    'noun.item': { one: 'тауар', few: 'тауар', many: 'тауарлар' },
    'noun.order': { one: 'тапсырыс', few: 'тапсырыс', many: 'тапсырыстар' },

    'category.phones-gadgets': 'Телефондар мен гаджеттер',
    'category.smartphones': 'Смартфондар',
    'category.smartphone-accessories': 'Смартфон аксессуарлары',
    'category.feature-phones': 'Түймелі телефондар',
    'category.smartwatches-bands': 'Смарт сағаттар мен білезіктер',
    'category.laptops-computers': 'Ноутбуктер мен компьютерлер',
    'category.laptops': 'Ноутбуктер',
    'category.tablets': 'Планшеттер',
    'category.desktops-all-in-ones': 'Үстел компьютерлері мен моноблоктар',
    'category.monitors': 'Мониторлар',
    'category.pc-components': 'ДК құрамдас бөліктері',
    'category.peripherals-accessories': 'Периферия және аксессуарлар',
    'category.audio-devices': 'Аудиотехника',
    'category.headphones-headsets': 'Құлаққаптар мен гарнитуралар',
    'category.portable-speakers': 'Портативті колонкалар',
    'category.home-audio-systems': 'Үй аудиожүйелері',
    'category.photo-video': 'Фото және видео',
    'category.cameras': 'Фотокамералар',
    'category.camcorders': 'Бейнекамералар',
    'category.action-cameras': 'Экшн-камералар',
    'category.drones-quadcopters': 'Дрондар мен квадрокоптерлер',
    'category.photo-video-accessories': 'Фото және видео аксессуарлары',
    'category.smart-home': 'Ақылды үй',
    'category.smart-security': 'Қауіпсіздік жүйелері',
    'category.smart-lighting': 'Ақылды жарықтандыру',
    'category.smart-plugs-switches': 'Ақылды розеткалар мен ажыратқыштар',
    'category.smart-climate': 'Климаттық бақылау',

    'color.midnight black': 'Түн қарасы',
    'color.nebula blue': 'Тұманды көк',
    'color.space gray': 'Ғарыш сұры',
    'color.graphite black': 'Графит қарасы',
    'color.obsidian black': 'Обсидиан қарасы',
    'color.natural titanium': 'Табиғи титан',
    'color.titanium gray': 'Титан сұры',
    'color.black': 'Қара',
    'color.asteroid black': 'Астероид қарасы',
    'color.starry night': 'Жұлдызды түн',
    'color.silver': 'Күміс',
    'color.space black': 'Ғарыш қарасы',
    'color.blue': 'Көк',
    'color.eclipse gray': 'Тұтылу сұры',
    'color.inkwell gray': 'Сия сұры',
    'color.cool silver': 'Салқын күміс',
    'color.grey': 'Сұр',
    'color.charcoal': 'Көмір',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  translate: (key: string, params?: Record<string, string | number | undefined>, options?: { defaultValue?: string }) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'appLanguage';

// Helper function for pluralization, moved from i18nUtils to be co-located.
function getPluralNoun(count: number, one: string, few: string, many: string): string {
  const n = Math.abs(count) % 100;
  const n1 = n % 10;

  if (n > 10 && n < 20) return many;
  if (n1 > 1 && n1 < 5) return few;
  if (n1 === 1) return one;
  return many;
}


export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ru');
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
    if (storedLanguage && dictionaries[storedLanguage]) {
      setLanguageState(storedLanguage);
      document.documentElement.lang = storedLanguage;
    } else {
      document.documentElement.lang = 'ru'; // Default if nothing stored
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    if (dictionaries[lang]) {
      setLanguageState(lang);
      if (typeof window !== "undefined") {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
        document.documentElement.lang = lang;
      }
    }
  }, []);

  const translate = useCallback((key: string, params?: Record<string, string | number | undefined>, options?: { defaultValue?: string }): string => {
    const currentDictionary = dictionaries[language] || dictionaries.ru;
    let translationValue = currentDictionary[key];
    const defaultValue = options?.defaultValue;

    if (translationValue === undefined) {
        return defaultValue !== undefined ? defaultValue : key;
    }

    if (typeof translationValue === 'object' && params && typeof params.count === 'number') {
        const count = params.count;
        translationValue = getPluralNoun(count, translationValue.one, translationValue.few, translationValue.many);
    }

    let translationString = typeof translationValue === 'string' ? translationValue : (defaultValue !== undefined ? defaultValue : key);


    if (params) {
      Object.keys(params).forEach(paramKey => {
        if (params[paramKey] !== undefined) {
            const regex = new RegExp(`{${paramKey}}`, 'g');
            translationString = translationString.replace(regex, String(params[paramKey]));
        }
      });
    }
    return translationString;
  }, [language]);


  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
